// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "SHA1ProcessMessageBlock.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic SHA1ProcessMessageBlock::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic SHA1ProcessMessageBlock::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st1_fsm_0 = "1";
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st2_fsm_1 = "10";
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st3_fsm_2 = "100";
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st4_fsm_3 = "1000";
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st5_fsm_4 = "10000";
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st6_fsm_5 = "100000";
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st16_fsm_15 = "1000000000000000";
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st17_fsm_16 = "10000000000000000";
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st18_fsm_17 = "100000000000000000";
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st19_fsm_18 = "1000000000000000000";
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st20_fsm_19 = "10000000000000000000";
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st21_fsm_20 = "100000000000000000000";
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st22_fsm_21 = "1000000000000000000000";
const sc_lv<23> SHA1ProcessMessageBlock::ap_ST_st23_fsm_22 = "10000000000000000000000";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> SHA1ProcessMessageBlock::ap_const_lv1_1 = "1";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_9 = "1001";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_C = "1100";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_F = "1111";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_12 = "10010";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_1 = "1";
const sc_lv<1> SHA1ProcessMessageBlock::ap_const_lv1_0 = "0";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_2 = "10";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_4 = "100";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_5 = "101";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_6 = "110";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_7 = "111";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_8 = "1000";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_A = "1010";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_B = "1011";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_D = "1101";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_E = "1110";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_10 = "10000";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_11 = "10001";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_13 = "10011";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_14 = "10100";
const sc_lv<5> SHA1ProcessMessageBlock::ap_const_lv5_0 = "00000";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_3 = "11";
const sc_lv<7> SHA1ProcessMessageBlock::ap_const_lv7_10 = "10000";
const sc_lv<6> SHA1ProcessMessageBlock::ap_const_lv6_14 = "10100";
const sc_lv<6> SHA1ProcessMessageBlock::ap_const_lv6_28 = "101000";
const sc_lv<7> SHA1ProcessMessageBlock::ap_const_lv7_3C = "111100";
const sc_lv<64> SHA1ProcessMessageBlock::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> SHA1ProcessMessageBlock::ap_const_lv64_1 = "1";
const sc_lv<64> SHA1ProcessMessageBlock::ap_const_lv64_2 = "10";
const sc_lv<64> SHA1ProcessMessageBlock::ap_const_lv64_3 = "11";
const sc_lv<64> SHA1ProcessMessageBlock::ap_const_lv64_4 = "100";
const sc_lv<16> SHA1ProcessMessageBlock::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_16 = "10110";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_15 = "10101";
const sc_lv<2> SHA1ProcessMessageBlock::ap_const_lv2_0 = "00";
const sc_lv<2> SHA1ProcessMessageBlock::ap_const_lv2_1 = "1";
const sc_lv<2> SHA1ProcessMessageBlock::ap_const_lv2_2 = "10";
const sc_lv<2> SHA1ProcessMessageBlock::ap_const_lv2_3 = "11";
const sc_lv<5> SHA1ProcessMessageBlock::ap_const_lv5_10 = "10000";
const sc_lv<5> SHA1ProcessMessageBlock::ap_const_lv5_1 = "1";
const sc_lv<6> SHA1ProcessMessageBlock::ap_const_lv6_1 = "1";
const sc_lv<6> SHA1ProcessMessageBlock::ap_const_lv6_2 = "10";
const sc_lv<6> SHA1ProcessMessageBlock::ap_const_lv6_3 = "11";
const sc_lv<7> SHA1ProcessMessageBlock::ap_const_lv7_50 = "1010000";
const sc_lv<7> SHA1ProcessMessageBlock::ap_const_lv7_7D = "1111101";
const sc_lv<7> SHA1ProcessMessageBlock::ap_const_lv7_78 = "1111000";
const sc_lv<7> SHA1ProcessMessageBlock::ap_const_lv7_72 = "1110010";
const sc_lv<7> SHA1ProcessMessageBlock::ap_const_lv7_70 = "1110000";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_1F = "11111";
const sc_lv<7> SHA1ProcessMessageBlock::ap_const_lv7_1 = "1";
const sc_lv<5> SHA1ProcessMessageBlock::ap_const_lv5_14 = "10100";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_1B = "11011";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<6> SHA1ProcessMessageBlock::ap_const_lv6_3C = "111100";

SHA1ProcessMessageBlock::SHA1ProcessMessageBlock(sc_module_name name) : sc_module(name), mVcdFile(0) {
    K_U = new SHA1ProcessMessageBlock_K("K_U");
    K_U->clk(ap_clk);
    K_U->reset(ap_rst);
    K_U->address0(K_address0);
    K_U->ce0(K_ce0);
    K_U->q0(K_q0);
    W_U = new SHA1ProcessMessageBlock_W("W_U");
    W_U->clk(ap_clk);
    W_U->reset(ap_rst);
    W_U->address0(W_address0);
    W_U->ce0(W_ce0);
    W_U->we0(W_we0);
    W_U->d0(W_d0);
    W_U->q0(W_q0);
    W_U->address1(W_address1);
    W_U->ce1(W_ce1);
    W_U->we1(W_we1);
    W_U->d1(W_d1);
    W_U->q1(W_q1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_C_1_fu_892_p3);
    sensitive << ( tmp_27_fu_878_p1 );
    sensitive << ( tmp_71_i_i_fu_882_p4 );

    SC_METHOD(thread_C_2_fu_983_p3);
    sensitive << ( tmp_43_fu_969_p1 );
    sensitive << ( tmp_71_i_i1_fu_973_p4 );

    SC_METHOD(thread_C_3_fu_1086_p3);
    sensitive << ( tmp_45_fu_1072_p1 );
    sensitive << ( tmp_71_i_i2_fu_1076_p4 );

    SC_METHOD(thread_C_4_fu_1165_p3);
    sensitive << ( tmp_47_fu_1151_p1 );
    sensitive << ( tmp_71_i_i3_fu_1155_p4 );

    SC_METHOD(thread_K_address0);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );

    SC_METHOD(thread_K_ce0);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );

    SC_METHOD(thread_W_address0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_5_fu_683_p1 );
    sensitive << ( tmp_11_fu_711_p1 );
    sensitive << ( tmp_17_fu_744_p1 );
    sensitive << ( tmp_25_fu_809_p1 );
    sensitive << ( tmp_34_fu_997_p1 );

    SC_METHOD(thread_W_address1);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );
    sensitive << ( tmp_13_fu_722_p1 );
    sensitive << ( tmp_15_fu_733_p1 );
    sensitive << ( tmp_19_fu_786_p1 );
    sensitive << ( tmp_29_fu_906_p1 );
    sensitive << ( tmp_41_fu_1134_p1 );

    SC_METHOD(thread_W_ce0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_W_ce1);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );

    SC_METHOD(thread_W_d0);
    sensitive << ( context_Message_Block_q0 );
    sensitive << ( context_Message_Block_q1 );
    sensitive << ( context_Message_Block_load_reg_1235 );
    sensitive << ( context_Message_Block_load_1_reg_1240 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_W_d1);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( tmp_18_fu_765_p1 );
    sensitive << ( tmp_20_fu_769_p3 );

    SC_METHOD(thread_W_we0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_W_we1);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );

    SC_METHOD(thread_ap_sig_105);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_115);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_133);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_147);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_165);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_180);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_188);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_200);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_216);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_230);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_241);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_255);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_266);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_280);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_291);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_317);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_343);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_38);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_428);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_450);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_82);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_89);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_97);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_82 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_216 );

    SC_METHOD(thread_ap_sig_cseq_ST_st12_fsm_11);
    sensitive << ( ap_sig_230 );

    SC_METHOD(thread_ap_sig_cseq_ST_st13_fsm_12);
    sensitive << ( ap_sig_89 );

    SC_METHOD(thread_ap_sig_cseq_ST_st14_fsm_13);
    sensitive << ( ap_sig_241 );

    SC_METHOD(thread_ap_sig_cseq_ST_st15_fsm_14);
    sensitive << ( ap_sig_255 );

    SC_METHOD(thread_ap_sig_cseq_ST_st16_fsm_15);
    sensitive << ( ap_sig_97 );

    SC_METHOD(thread_ap_sig_cseq_ST_st17_fsm_16);
    sensitive << ( ap_sig_266 );

    SC_METHOD(thread_ap_sig_cseq_ST_st18_fsm_17);
    sensitive << ( ap_sig_280 );

    SC_METHOD(thread_ap_sig_cseq_ST_st19_fsm_18);
    sensitive << ( ap_sig_105 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_38 );

    SC_METHOD(thread_ap_sig_cseq_ST_st20_fsm_19);
    sensitive << ( ap_sig_291 );

    SC_METHOD(thread_ap_sig_cseq_ST_st21_fsm_20);
    sensitive << ( ap_sig_317 );

    SC_METHOD(thread_ap_sig_cseq_ST_st22_fsm_21);
    sensitive << ( ap_sig_450 );

    SC_METHOD(thread_ap_sig_cseq_ST_st23_fsm_22);
    sensitive << ( ap_sig_428 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_115 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_133 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_343 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_147 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_165 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_180 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_188 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_200 );

    SC_METHOD(thread_context_Intermediate_Hash_addr_1_reg_1305);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_context_Intermediate_Hash_addr_2_reg_1310);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_context_Intermediate_Hash_address0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( context_Intermediate_Hash_addr_1_reg_1305 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );

    SC_METHOD(thread_context_Intermediate_Hash_address1);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( context_Intermediate_Hash_addr_2_reg_1310 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );

    SC_METHOD(thread_context_Intermediate_Hash_ce0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );

    SC_METHOD(thread_context_Intermediate_Hash_ce1);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );

    SC_METHOD(thread_context_Intermediate_Hash_d0);
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );
    sensitive << ( tmp_38_reg_1448 );
    sensitive << ( tmp_36_fu_1185_p2 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );

    SC_METHOD(thread_context_Intermediate_Hash_d1);
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );
    sensitive << ( tmp_37_reg_1443 );
    sensitive << ( tmp_39_reg_1453 );
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );
    sensitive << ( tmp_35_fu_1179_p2 );

    SC_METHOD(thread_context_Intermediate_Hash_we0);
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );
    sensitive << ( exitcond_fu_1094_p2 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );

    SC_METHOD(thread_context_Intermediate_Hash_we1);
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );
    sensitive << ( exitcond_fu_1094_p2 );
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );

    SC_METHOD(thread_context_Message_Block_Index);
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );

    SC_METHOD(thread_context_Message_Block_Index_ap_vld);
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );

    SC_METHOD(thread_context_Message_Block_address0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_2_fu_647_p1 );
    sensitive << ( tmp_3_fu_668_p1 );

    SC_METHOD(thread_context_Message_Block_address1);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_7_fu_658_p1 );
    sensitive << ( tmp_8_fu_678_p1 );

    SC_METHOD(thread_context_Message_Block_ce0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_context_Message_Block_ce1);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_exitcond1_fu_991_p2);
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( t_4_reg_529 );

    SC_METHOD(thread_exitcond2_fu_900_p2);
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( t_3_reg_460 );

    SC_METHOD(thread_exitcond3_fu_797_p2);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( t_2_reg_391 );

    SC_METHOD(thread_exitcond4_fu_699_p2);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( t_1_reg_326 );

    SC_METHOD(thread_exitcond5_fu_623_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( t_reg_314 );

    SC_METHOD(thread_exitcond_fu_1094_p2);
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );
    sensitive << ( t_5_reg_596 );

    SC_METHOD(thread_grp_fu_611_p2);
    sensitive << ( reg_607 );
    sensitive << ( W_q0 );

    SC_METHOD(thread_grp_fu_617_p2);
    sensitive << ( reg_607 );
    sensitive << ( W_q1 );

    SC_METHOD(thread_t_10_fu_1002_p2);
    sensitive << ( t_4_reg_529 );

    SC_METHOD(thread_t_11_fu_1173_p2);
    sensitive << ( t_5_reg_596 );

    SC_METHOD(thread_t_6_fu_629_p2);
    sensitive << ( t_reg_314 );

    SC_METHOD(thread_t_7_fu_791_p2);
    sensitive << ( t_1_reg_326 );

    SC_METHOD(thread_t_8_fu_803_p2);
    sensitive << ( t_2_reg_391 );

    SC_METHOD(thread_t_9_fu_911_p2);
    sensitive << ( t_3_reg_460 );

    SC_METHOD(thread_temp_1_fu_963_p2);
    sensitive << ( tmp10_fu_957_p2 );
    sensitive << ( grp_fu_617_p2 );

    SC_METHOD(thread_temp_2_fu_1066_p2);
    sensitive << ( grp_fu_611_p2 );
    sensitive << ( tmp13_fu_1060_p2 );

    SC_METHOD(thread_temp_3_fu_1206_p2);
    sensitive << ( tmp17_reg_1428 );
    sensitive << ( grp_fu_617_p2 );

    SC_METHOD(thread_temp_fu_872_p2);
    sensitive << ( tmp6_fu_866_p2 );
    sensitive << ( grp_fu_611_p2 );

    SC_METHOD(thread_tmp10_fu_957_p2);
    sensitive << ( tmp11_fu_951_p2 );
    sensitive << ( tmp_72_i2_fu_931_p3 );

    SC_METHOD(thread_tmp11_fu_951_p2);
    sensitive << ( E_s_reg_402 );
    sensitive << ( tmp_28_fu_945_p2 );

    SC_METHOD(thread_tmp13_fu_1060_p2);
    sensitive << ( tmp14_fu_1054_p2 );
    sensitive << ( tmp_72_i3_fu_1022_p3 );

    SC_METHOD(thread_tmp14_fu_1054_p2);
    sensitive << ( E_2_reg_471 );
    sensitive << ( tmp_33_fu_1048_p2 );

    SC_METHOD(thread_tmp15_fu_1122_p2);
    sensitive << ( E_6_reg_550 );
    sensitive << ( B_read_assign_3_reg_574 );

    SC_METHOD(thread_tmp17_fu_1145_p2);
    sensitive << ( tmp18_fu_1139_p2 );
    sensitive << ( tmp_72_i4_fu_1114_p3 );

    SC_METHOD(thread_tmp18_fu_1139_p2);
    sensitive << ( E_3_reg_540 );
    sensitive << ( tmp_40_fu_1128_p2 );

    SC_METHOD(thread_tmp3_fu_749_p2);
    sensitive << ( W_load_reg_1274 );
    sensitive << ( W_q1 );

    SC_METHOD(thread_tmp4_fu_754_p2);
    sensitive << ( W_q0 );
    sensitive << ( W_load_1_reg_1279 );

    SC_METHOD(thread_tmp6_fu_866_p2);
    sensitive << ( tmp7_fu_860_p2 );
    sensitive << ( tmp_72_i1_fu_828_p3 );

    SC_METHOD(thread_tmp7_fu_860_p2);
    sensitive << ( E1_reg_338 );
    sensitive << ( tmp_24_fu_854_p2 );

    SC_METHOD(thread_tmp8_fu_939_p2);
    sensitive << ( E_4_reg_413 );
    sensitive << ( B_read_assign_1_reg_437 );

    SC_METHOD(thread_tmp_10_fu_705_p2);
    sensitive << ( t_1_reg_326 );

    SC_METHOD(thread_tmp_11_fu_711_p1);
    sensitive << ( tmp_10_fu_705_p2 );

    SC_METHOD(thread_tmp_12_fu_716_p2);
    sensitive << ( t_1_reg_326 );

    SC_METHOD(thread_tmp_13_fu_722_p1);
    sensitive << ( tmp_12_fu_716_p2 );

    SC_METHOD(thread_tmp_14_fu_727_p2);
    sensitive << ( t_1_reg_326 );

    SC_METHOD(thread_tmp_15_fu_733_p1);
    sensitive << ( tmp_14_fu_727_p2 );

    SC_METHOD(thread_tmp_16_fu_738_p2);
    sensitive << ( t_1_reg_326 );

    SC_METHOD(thread_tmp_17_fu_744_p1);
    sensitive << ( tmp_16_fu_738_p2 );

    SC_METHOD(thread_tmp_18_fu_765_p1);
    sensitive << ( word_assign_fu_759_p2 );

    SC_METHOD(thread_tmp_19_fu_786_p1);
    sensitive << ( t_1_reg_326 );

    SC_METHOD(thread_tmp_1_fu_639_p3);
    sensitive << ( tmp_fu_635_p1 );

    SC_METHOD(thread_tmp_20_fu_769_p3);
    sensitive << ( word_assign_fu_759_p2 );

    SC_METHOD(thread_tmp_21_fu_836_p2);
    sensitive << ( D_1_reg_359 );
    sensitive << ( B_read_assign_reg_370 );

    SC_METHOD(thread_tmp_22_fu_842_p2);
    sensitive << ( B_read_assign_reg_370 );

    SC_METHOD(thread_tmp_23_fu_848_p2);
    sensitive << ( E_1_reg_348 );
    sensitive << ( tmp_22_fu_842_p2 );

    SC_METHOD(thread_tmp_24_fu_854_p2);
    sensitive << ( tmp_23_fu_848_p2 );
    sensitive << ( tmp_21_fu_836_p2 );

    SC_METHOD(thread_tmp_25_fu_809_p1);
    sensitive << ( t_2_reg_391 );

    SC_METHOD(thread_tmp_26_fu_814_p1);
    sensitive << ( B_1_reg_380 );

    SC_METHOD(thread_tmp_27_fu_878_p1);
    sensitive << ( B_read_assign_reg_370 );

    SC_METHOD(thread_tmp_28_fu_945_p2);
    sensitive << ( D_2_reg_425 );
    sensitive << ( tmp8_fu_939_p2 );

    SC_METHOD(thread_tmp_29_fu_906_p1);
    sensitive << ( t_3_reg_460 );

    SC_METHOD(thread_tmp_2_fu_647_p1);
    sensitive << ( tmp_1_fu_639_p3 );

    SC_METHOD(thread_tmp_30_fu_1030_p2);
    sensitive << ( E_5_reg_482 );
    sensitive << ( D_3_reg_494 );

    SC_METHOD(thread_tmp_31_fu_1036_p2);
    sensitive << ( B_read_assign_2_reg_506 );
    sensitive << ( tmp_30_fu_1030_p2 );

    SC_METHOD(thread_tmp_32_fu_1042_p2);
    sensitive << ( E_5_reg_482 );
    sensitive << ( D_3_reg_494 );

    SC_METHOD(thread_tmp_33_fu_1048_p2);
    sensitive << ( tmp_31_fu_1036_p2 );
    sensitive << ( tmp_32_fu_1042_p2 );

    SC_METHOD(thread_tmp_34_fu_997_p1);
    sensitive << ( t_4_reg_529 );

    SC_METHOD(thread_tmp_35_fu_1179_p2);
    sensitive << ( A_reg_1299 );
    sensitive << ( B_4_reg_584 );

    SC_METHOD(thread_tmp_36_fu_1185_p2);
    sensitive << ( B_reg_1315 );
    sensitive << ( B_read_assign_3_reg_574 );

    SC_METHOD(thread_tmp_37_fu_1191_p2);
    sensitive << ( C_reg_1321 );
    sensitive << ( D_4_reg_562 );

    SC_METHOD(thread_tmp_38_fu_1196_p2);
    sensitive << ( D_reg_1339 );
    sensitive << ( E_6_reg_550 );

    SC_METHOD(thread_tmp_39_fu_1201_p2);
    sensitive << ( E_reg_1345 );
    sensitive << ( E_3_reg_540 );

    SC_METHOD(thread_tmp_3_fu_668_p1);
    sensitive << ( tmp_s_fu_663_p2 );

    SC_METHOD(thread_tmp_40_fu_1128_p2);
    sensitive << ( D_4_reg_562 );
    sensitive << ( tmp15_fu_1122_p2 );

    SC_METHOD(thread_tmp_41_fu_1134_p1);
    sensitive << ( t_5_reg_596 );

    SC_METHOD(thread_tmp_42_fu_917_p1);
    sensitive << ( B_2_reg_448 );

    SC_METHOD(thread_tmp_43_fu_969_p1);
    sensitive << ( B_read_assign_1_reg_437 );

    SC_METHOD(thread_tmp_44_fu_1008_p1);
    sensitive << ( B_3_reg_517 );

    SC_METHOD(thread_tmp_45_fu_1072_p1);
    sensitive << ( B_read_assign_2_reg_506 );

    SC_METHOD(thread_tmp_46_fu_1100_p1);
    sensitive << ( B_4_reg_584 );

    SC_METHOD(thread_tmp_47_fu_1151_p1);
    sensitive << ( B_read_assign_3_reg_574 );

    SC_METHOD(thread_tmp_4_fu_673_p2);
    sensitive << ( tmp_1_reg_1219 );

    SC_METHOD(thread_tmp_5_fu_683_p1);
    sensitive << ( t_reg_314 );

    SC_METHOD(thread_tmp_6_fu_652_p2);
    sensitive << ( tmp_1_fu_639_p3 );

    SC_METHOD(thread_tmp_71_i1_fu_818_p4);
    sensitive << ( B_1_reg_380 );

    SC_METHOD(thread_tmp_71_i2_fu_921_p4);
    sensitive << ( B_2_reg_448 );

    SC_METHOD(thread_tmp_71_i3_fu_1012_p4);
    sensitive << ( B_3_reg_517 );

    SC_METHOD(thread_tmp_71_i4_fu_1104_p4);
    sensitive << ( B_4_reg_584 );

    SC_METHOD(thread_tmp_71_i_i1_fu_973_p4);
    sensitive << ( B_read_assign_1_reg_437 );

    SC_METHOD(thread_tmp_71_i_i2_fu_1076_p4);
    sensitive << ( B_read_assign_2_reg_506 );

    SC_METHOD(thread_tmp_71_i_i3_fu_1155_p4);
    sensitive << ( B_read_assign_3_reg_574 );

    SC_METHOD(thread_tmp_71_i_i_fu_882_p4);
    sensitive << ( B_read_assign_reg_370 );

    SC_METHOD(thread_tmp_72_i1_fu_828_p3);
    sensitive << ( tmp_26_fu_814_p1 );
    sensitive << ( tmp_71_i1_fu_818_p4 );

    SC_METHOD(thread_tmp_72_i2_fu_931_p3);
    sensitive << ( tmp_42_fu_917_p1 );
    sensitive << ( tmp_71_i2_fu_921_p4 );

    SC_METHOD(thread_tmp_72_i3_fu_1022_p3);
    sensitive << ( tmp_44_fu_1008_p1 );
    sensitive << ( tmp_71_i3_fu_1012_p4 );

    SC_METHOD(thread_tmp_72_i4_fu_1114_p3);
    sensitive << ( tmp_46_fu_1100_p1 );
    sensitive << ( tmp_71_i4_fu_1104_p4 );

    SC_METHOD(thread_tmp_7_fu_658_p1);
    sensitive << ( tmp_6_fu_652_p2 );

    SC_METHOD(thread_tmp_8_fu_678_p1);
    sensitive << ( tmp_4_fu_673_p2 );

    SC_METHOD(thread_tmp_fu_635_p1);
    sensitive << ( t_reg_314 );

    SC_METHOD(thread_tmp_s_fu_663_p2);
    sensitive << ( tmp_1_reg_1219 );

    SC_METHOD(thread_word_assign_fu_759_p2);
    sensitive << ( tmp4_fu_754_p2 );
    sensitive << ( tmp3_fu_749_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond5_fu_623_p2 );
    sensitive << ( exitcond4_fu_699_p2 );
    sensitive << ( exitcond3_fu_797_p2 );
    sensitive << ( exitcond2_fu_900_p2 );
    sensitive << ( exitcond1_fu_991_p2 );
    sensitive << ( exitcond_fu_1094_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "00000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "SHA1ProcessMessageBlock_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, context_Intermediate_Hash_address0, "(port)context_Intermediate_Hash_address0");
    sc_trace(mVcdFile, context_Intermediate_Hash_ce0, "(port)context_Intermediate_Hash_ce0");
    sc_trace(mVcdFile, context_Intermediate_Hash_we0, "(port)context_Intermediate_Hash_we0");
    sc_trace(mVcdFile, context_Intermediate_Hash_d0, "(port)context_Intermediate_Hash_d0");
    sc_trace(mVcdFile, context_Intermediate_Hash_q0, "(port)context_Intermediate_Hash_q0");
    sc_trace(mVcdFile, context_Intermediate_Hash_address1, "(port)context_Intermediate_Hash_address1");
    sc_trace(mVcdFile, context_Intermediate_Hash_ce1, "(port)context_Intermediate_Hash_ce1");
    sc_trace(mVcdFile, context_Intermediate_Hash_we1, "(port)context_Intermediate_Hash_we1");
    sc_trace(mVcdFile, context_Intermediate_Hash_d1, "(port)context_Intermediate_Hash_d1");
    sc_trace(mVcdFile, context_Intermediate_Hash_q1, "(port)context_Intermediate_Hash_q1");
    sc_trace(mVcdFile, context_Message_Block_Index, "(port)context_Message_Block_Index");
    sc_trace(mVcdFile, context_Message_Block_Index_ap_vld, "(port)context_Message_Block_Index_ap_vld");
    sc_trace(mVcdFile, context_Message_Block_address0, "(port)context_Message_Block_address0");
    sc_trace(mVcdFile, context_Message_Block_ce0, "(port)context_Message_Block_ce0");
    sc_trace(mVcdFile, context_Message_Block_q0, "(port)context_Message_Block_q0");
    sc_trace(mVcdFile, context_Message_Block_address1, "(port)context_Message_Block_address1");
    sc_trace(mVcdFile, context_Message_Block_ce1, "(port)context_Message_Block_ce1");
    sc_trace(mVcdFile, context_Message_Block_q1, "(port)context_Message_Block_q1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_38, "ap_sig_38");
    sc_trace(mVcdFile, K_address0, "K_address0");
    sc_trace(mVcdFile, K_ce0, "K_ce0");
    sc_trace(mVcdFile, K_q0, "K_q0");
    sc_trace(mVcdFile, reg_607, "reg_607");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_82, "ap_sig_82");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st13_fsm_12, "ap_sig_cseq_ST_st13_fsm_12");
    sc_trace(mVcdFile, ap_sig_89, "ap_sig_89");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st16_fsm_15, "ap_sig_cseq_ST_st16_fsm_15");
    sc_trace(mVcdFile, ap_sig_97, "ap_sig_97");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st19_fsm_18, "ap_sig_cseq_ST_st19_fsm_18");
    sc_trace(mVcdFile, ap_sig_105, "ap_sig_105");
    sc_trace(mVcdFile, t_6_fu_629_p2, "t_6_fu_629_p2");
    sc_trace(mVcdFile, t_6_reg_1214, "t_6_reg_1214");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_115, "ap_sig_115");
    sc_trace(mVcdFile, tmp_1_fu_639_p3, "tmp_1_fu_639_p3");
    sc_trace(mVcdFile, tmp_1_reg_1219, "tmp_1_reg_1219");
    sc_trace(mVcdFile, exitcond5_fu_623_p2, "exitcond5_fu_623_p2");
    sc_trace(mVcdFile, context_Message_Block_load_reg_1235, "context_Message_Block_load_reg_1235");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_133, "ap_sig_133");
    sc_trace(mVcdFile, context_Message_Block_load_1_reg_1240, "context_Message_Block_load_1_reg_1240");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_147, "ap_sig_147");
    sc_trace(mVcdFile, exitcond4_fu_699_p2, "exitcond4_fu_699_p2");
    sc_trace(mVcdFile, W_q0, "W_q0");
    sc_trace(mVcdFile, W_load_reg_1274, "W_load_reg_1274");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_165, "ap_sig_165");
    sc_trace(mVcdFile, W_q1, "W_q1");
    sc_trace(mVcdFile, W_load_1_reg_1279, "W_load_1_reg_1279");
    sc_trace(mVcdFile, t_7_fu_791_p2, "t_7_fu_791_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_180, "ap_sig_180");
    sc_trace(mVcdFile, A_reg_1299, "A_reg_1299");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_188, "ap_sig_188");
    sc_trace(mVcdFile, context_Intermediate_Hash_addr_1_reg_1305, "context_Intermediate_Hash_addr_1_reg_1305");
    sc_trace(mVcdFile, context_Intermediate_Hash_addr_2_reg_1310, "context_Intermediate_Hash_addr_2_reg_1310");
    sc_trace(mVcdFile, B_reg_1315, "B_reg_1315");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_200, "ap_sig_200");
    sc_trace(mVcdFile, C_reg_1321, "C_reg_1321");
    sc_trace(mVcdFile, D_reg_1339, "D_reg_1339");
    sc_trace(mVcdFile, E_reg_1345, "E_reg_1345");
    sc_trace(mVcdFile, t_8_fu_803_p2, "t_8_fu_803_p2");
    sc_trace(mVcdFile, t_8_reg_1354, "t_8_reg_1354");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_216, "ap_sig_216");
    sc_trace(mVcdFile, exitcond3_fu_797_p2, "exitcond3_fu_797_p2");
    sc_trace(mVcdFile, temp_fu_872_p2, "temp_fu_872_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st12_fsm_11, "ap_sig_cseq_ST_st12_fsm_11");
    sc_trace(mVcdFile, ap_sig_230, "ap_sig_230");
    sc_trace(mVcdFile, C_1_fu_892_p3, "C_1_fu_892_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st14_fsm_13, "ap_sig_cseq_ST_st14_fsm_13");
    sc_trace(mVcdFile, ap_sig_241, "ap_sig_241");
    sc_trace(mVcdFile, exitcond2_fu_900_p2, "exitcond2_fu_900_p2");
    sc_trace(mVcdFile, t_9_fu_911_p2, "t_9_fu_911_p2");
    sc_trace(mVcdFile, t_9_reg_1382, "t_9_reg_1382");
    sc_trace(mVcdFile, temp_1_fu_963_p2, "temp_1_fu_963_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st15_fsm_14, "ap_sig_cseq_ST_st15_fsm_14");
    sc_trace(mVcdFile, ap_sig_255, "ap_sig_255");
    sc_trace(mVcdFile, C_2_fu_983_p3, "C_2_fu_983_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st17_fsm_16, "ap_sig_cseq_ST_st17_fsm_16");
    sc_trace(mVcdFile, ap_sig_266, "ap_sig_266");
    sc_trace(mVcdFile, exitcond1_fu_991_p2, "exitcond1_fu_991_p2");
    sc_trace(mVcdFile, t_10_fu_1002_p2, "t_10_fu_1002_p2");
    sc_trace(mVcdFile, t_10_reg_1405, "t_10_reg_1405");
    sc_trace(mVcdFile, temp_2_fu_1066_p2, "temp_2_fu_1066_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st18_fsm_17, "ap_sig_cseq_ST_st18_fsm_17");
    sc_trace(mVcdFile, ap_sig_280, "ap_sig_280");
    sc_trace(mVcdFile, C_3_fu_1086_p3, "C_3_fu_1086_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st20_fsm_19, "ap_sig_cseq_ST_st20_fsm_19");
    sc_trace(mVcdFile, ap_sig_291, "ap_sig_291");
    sc_trace(mVcdFile, exitcond_fu_1094_p2, "exitcond_fu_1094_p2");
    sc_trace(mVcdFile, tmp17_fu_1145_p2, "tmp17_fu_1145_p2");
    sc_trace(mVcdFile, tmp17_reg_1428, "tmp17_reg_1428");
    sc_trace(mVcdFile, C_4_fu_1165_p3, "C_4_fu_1165_p3");
    sc_trace(mVcdFile, C_4_reg_1433, "C_4_reg_1433");
    sc_trace(mVcdFile, t_11_fu_1173_p2, "t_11_fu_1173_p2");
    sc_trace(mVcdFile, t_11_reg_1438, "t_11_reg_1438");
    sc_trace(mVcdFile, tmp_37_fu_1191_p2, "tmp_37_fu_1191_p2");
    sc_trace(mVcdFile, tmp_37_reg_1443, "tmp_37_reg_1443");
    sc_trace(mVcdFile, tmp_38_fu_1196_p2, "tmp_38_fu_1196_p2");
    sc_trace(mVcdFile, tmp_38_reg_1448, "tmp_38_reg_1448");
    sc_trace(mVcdFile, tmp_39_fu_1201_p2, "tmp_39_fu_1201_p2");
    sc_trace(mVcdFile, tmp_39_reg_1453, "tmp_39_reg_1453");
    sc_trace(mVcdFile, temp_3_fu_1206_p2, "temp_3_fu_1206_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st21_fsm_20, "ap_sig_cseq_ST_st21_fsm_20");
    sc_trace(mVcdFile, ap_sig_317, "ap_sig_317");
    sc_trace(mVcdFile, W_address0, "W_address0");
    sc_trace(mVcdFile, W_ce0, "W_ce0");
    sc_trace(mVcdFile, W_we0, "W_we0");
    sc_trace(mVcdFile, W_d0, "W_d0");
    sc_trace(mVcdFile, W_address1, "W_address1");
    sc_trace(mVcdFile, W_ce1, "W_ce1");
    sc_trace(mVcdFile, W_we1, "W_we1");
    sc_trace(mVcdFile, W_d1, "W_d1");
    sc_trace(mVcdFile, t_reg_314, "t_reg_314");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_343, "ap_sig_343");
    sc_trace(mVcdFile, t_1_reg_326, "t_1_reg_326");
    sc_trace(mVcdFile, E1_reg_338, "E1_reg_338");
    sc_trace(mVcdFile, E_1_reg_348, "E_1_reg_348");
    sc_trace(mVcdFile, D_1_reg_359, "D_1_reg_359");
    sc_trace(mVcdFile, B_read_assign_reg_370, "B_read_assign_reg_370");
    sc_trace(mVcdFile, B_1_reg_380, "B_1_reg_380");
    sc_trace(mVcdFile, t_2_reg_391, "t_2_reg_391");
    sc_trace(mVcdFile, E_s_reg_402, "E_s_reg_402");
    sc_trace(mVcdFile, E_4_reg_413, "E_4_reg_413");
    sc_trace(mVcdFile, D_2_reg_425, "D_2_reg_425");
    sc_trace(mVcdFile, B_read_assign_1_reg_437, "B_read_assign_1_reg_437");
    sc_trace(mVcdFile, B_2_reg_448, "B_2_reg_448");
    sc_trace(mVcdFile, t_3_reg_460, "t_3_reg_460");
    sc_trace(mVcdFile, E_2_reg_471, "E_2_reg_471");
    sc_trace(mVcdFile, E_5_reg_482, "E_5_reg_482");
    sc_trace(mVcdFile, D_3_reg_494, "D_3_reg_494");
    sc_trace(mVcdFile, B_read_assign_2_reg_506, "B_read_assign_2_reg_506");
    sc_trace(mVcdFile, B_3_reg_517, "B_3_reg_517");
    sc_trace(mVcdFile, t_4_reg_529, "t_4_reg_529");
    sc_trace(mVcdFile, E_3_reg_540, "E_3_reg_540");
    sc_trace(mVcdFile, E_6_reg_550, "E_6_reg_550");
    sc_trace(mVcdFile, D_4_reg_562, "D_4_reg_562");
    sc_trace(mVcdFile, B_read_assign_3_reg_574, "B_read_assign_3_reg_574");
    sc_trace(mVcdFile, B_4_reg_584, "B_4_reg_584");
    sc_trace(mVcdFile, t_5_reg_596, "t_5_reg_596");
    sc_trace(mVcdFile, tmp_2_fu_647_p1, "tmp_2_fu_647_p1");
    sc_trace(mVcdFile, tmp_7_fu_658_p1, "tmp_7_fu_658_p1");
    sc_trace(mVcdFile, tmp_3_fu_668_p1, "tmp_3_fu_668_p1");
    sc_trace(mVcdFile, tmp_8_fu_678_p1, "tmp_8_fu_678_p1");
    sc_trace(mVcdFile, tmp_5_fu_683_p1, "tmp_5_fu_683_p1");
    sc_trace(mVcdFile, tmp_11_fu_711_p1, "tmp_11_fu_711_p1");
    sc_trace(mVcdFile, tmp_13_fu_722_p1, "tmp_13_fu_722_p1");
    sc_trace(mVcdFile, tmp_15_fu_733_p1, "tmp_15_fu_733_p1");
    sc_trace(mVcdFile, tmp_17_fu_744_p1, "tmp_17_fu_744_p1");
    sc_trace(mVcdFile, tmp_19_fu_786_p1, "tmp_19_fu_786_p1");
    sc_trace(mVcdFile, tmp_25_fu_809_p1, "tmp_25_fu_809_p1");
    sc_trace(mVcdFile, tmp_29_fu_906_p1, "tmp_29_fu_906_p1");
    sc_trace(mVcdFile, tmp_34_fu_997_p1, "tmp_34_fu_997_p1");
    sc_trace(mVcdFile, tmp_41_fu_1134_p1, "tmp_41_fu_1134_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st23_fsm_22, "ap_sig_cseq_ST_st23_fsm_22");
    sc_trace(mVcdFile, ap_sig_428, "ap_sig_428");
    sc_trace(mVcdFile, tmp_36_fu_1185_p2, "tmp_36_fu_1185_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st22_fsm_21, "ap_sig_cseq_ST_st22_fsm_21");
    sc_trace(mVcdFile, ap_sig_450, "ap_sig_450");
    sc_trace(mVcdFile, tmp_35_fu_1179_p2, "tmp_35_fu_1179_p2");
    sc_trace(mVcdFile, tmp_fu_635_p1, "tmp_fu_635_p1");
    sc_trace(mVcdFile, tmp_6_fu_652_p2, "tmp_6_fu_652_p2");
    sc_trace(mVcdFile, tmp_s_fu_663_p2, "tmp_s_fu_663_p2");
    sc_trace(mVcdFile, tmp_4_fu_673_p2, "tmp_4_fu_673_p2");
    sc_trace(mVcdFile, tmp_10_fu_705_p2, "tmp_10_fu_705_p2");
    sc_trace(mVcdFile, tmp_12_fu_716_p2, "tmp_12_fu_716_p2");
    sc_trace(mVcdFile, tmp_14_fu_727_p2, "tmp_14_fu_727_p2");
    sc_trace(mVcdFile, tmp_16_fu_738_p2, "tmp_16_fu_738_p2");
    sc_trace(mVcdFile, tmp4_fu_754_p2, "tmp4_fu_754_p2");
    sc_trace(mVcdFile, tmp3_fu_749_p2, "tmp3_fu_749_p2");
    sc_trace(mVcdFile, word_assign_fu_759_p2, "word_assign_fu_759_p2");
    sc_trace(mVcdFile, tmp_18_fu_765_p1, "tmp_18_fu_765_p1");
    sc_trace(mVcdFile, tmp_20_fu_769_p3, "tmp_20_fu_769_p3");
    sc_trace(mVcdFile, tmp_26_fu_814_p1, "tmp_26_fu_814_p1");
    sc_trace(mVcdFile, tmp_71_i1_fu_818_p4, "tmp_71_i1_fu_818_p4");
    sc_trace(mVcdFile, tmp_22_fu_842_p2, "tmp_22_fu_842_p2");
    sc_trace(mVcdFile, tmp_23_fu_848_p2, "tmp_23_fu_848_p2");
    sc_trace(mVcdFile, tmp_21_fu_836_p2, "tmp_21_fu_836_p2");
    sc_trace(mVcdFile, tmp_24_fu_854_p2, "tmp_24_fu_854_p2");
    sc_trace(mVcdFile, tmp7_fu_860_p2, "tmp7_fu_860_p2");
    sc_trace(mVcdFile, tmp_72_i1_fu_828_p3, "tmp_72_i1_fu_828_p3");
    sc_trace(mVcdFile, tmp6_fu_866_p2, "tmp6_fu_866_p2");
    sc_trace(mVcdFile, grp_fu_611_p2, "grp_fu_611_p2");
    sc_trace(mVcdFile, tmp_27_fu_878_p1, "tmp_27_fu_878_p1");
    sc_trace(mVcdFile, tmp_71_i_i_fu_882_p4, "tmp_71_i_i_fu_882_p4");
    sc_trace(mVcdFile, tmp_42_fu_917_p1, "tmp_42_fu_917_p1");
    sc_trace(mVcdFile, tmp_71_i2_fu_921_p4, "tmp_71_i2_fu_921_p4");
    sc_trace(mVcdFile, tmp8_fu_939_p2, "tmp8_fu_939_p2");
    sc_trace(mVcdFile, tmp_28_fu_945_p2, "tmp_28_fu_945_p2");
    sc_trace(mVcdFile, tmp11_fu_951_p2, "tmp11_fu_951_p2");
    sc_trace(mVcdFile, tmp_72_i2_fu_931_p3, "tmp_72_i2_fu_931_p3");
    sc_trace(mVcdFile, tmp10_fu_957_p2, "tmp10_fu_957_p2");
    sc_trace(mVcdFile, grp_fu_617_p2, "grp_fu_617_p2");
    sc_trace(mVcdFile, tmp_43_fu_969_p1, "tmp_43_fu_969_p1");
    sc_trace(mVcdFile, tmp_71_i_i1_fu_973_p4, "tmp_71_i_i1_fu_973_p4");
    sc_trace(mVcdFile, tmp_44_fu_1008_p1, "tmp_44_fu_1008_p1");
    sc_trace(mVcdFile, tmp_71_i3_fu_1012_p4, "tmp_71_i3_fu_1012_p4");
    sc_trace(mVcdFile, tmp_30_fu_1030_p2, "tmp_30_fu_1030_p2");
    sc_trace(mVcdFile, tmp_31_fu_1036_p2, "tmp_31_fu_1036_p2");
    sc_trace(mVcdFile, tmp_32_fu_1042_p2, "tmp_32_fu_1042_p2");
    sc_trace(mVcdFile, tmp_33_fu_1048_p2, "tmp_33_fu_1048_p2");
    sc_trace(mVcdFile, tmp14_fu_1054_p2, "tmp14_fu_1054_p2");
    sc_trace(mVcdFile, tmp_72_i3_fu_1022_p3, "tmp_72_i3_fu_1022_p3");
    sc_trace(mVcdFile, tmp13_fu_1060_p2, "tmp13_fu_1060_p2");
    sc_trace(mVcdFile, tmp_45_fu_1072_p1, "tmp_45_fu_1072_p1");
    sc_trace(mVcdFile, tmp_71_i_i2_fu_1076_p4, "tmp_71_i_i2_fu_1076_p4");
    sc_trace(mVcdFile, tmp_46_fu_1100_p1, "tmp_46_fu_1100_p1");
    sc_trace(mVcdFile, tmp_71_i4_fu_1104_p4, "tmp_71_i4_fu_1104_p4");
    sc_trace(mVcdFile, tmp15_fu_1122_p2, "tmp15_fu_1122_p2");
    sc_trace(mVcdFile, tmp_40_fu_1128_p2, "tmp_40_fu_1128_p2");
    sc_trace(mVcdFile, tmp18_fu_1139_p2, "tmp18_fu_1139_p2");
    sc_trace(mVcdFile, tmp_72_i4_fu_1114_p3, "tmp_72_i4_fu_1114_p3");
    sc_trace(mVcdFile, tmp_47_fu_1151_p1, "tmp_47_fu_1151_p1");
    sc_trace(mVcdFile, tmp_71_i_i3_fu_1155_p4, "tmp_71_i_i3_fu_1155_p4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("SHA1ProcessMessageBlock.hdltvin.dat");
    mHdltvoutHandle.open("SHA1ProcessMessageBlock.hdltvout.dat");
}

SHA1ProcessMessageBlock::~SHA1ProcessMessageBlock() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete K_U;
    delete W_U;
}

void SHA1ProcessMessageBlock::thread_ap_clk_no_reset_() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        B_1_reg_380 = temp_fu_872_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        B_1_reg_380 = A_reg_1299.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        B_2_reg_448 = temp_1_fu_963_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        B_2_reg_448 = B_1_reg_380.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        B_3_reg_517 = temp_2_fu_1066_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        B_3_reg_517 = B_2_reg_448.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        B_4_reg_584 = temp_3_fu_1206_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        B_4_reg_584 = B_3_reg_517.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        B_read_assign_1_reg_437 = B_2_reg_448.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        B_read_assign_1_reg_437 = B_read_assign_reg_370.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        B_read_assign_2_reg_506 = B_3_reg_517.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        B_read_assign_2_reg_506 = B_read_assign_1_reg_437.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        B_read_assign_3_reg_574 = B_4_reg_584.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        B_read_assign_3_reg_574 = B_read_assign_2_reg_506.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        B_read_assign_reg_370 = B_1_reg_380.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        B_read_assign_reg_370 = B_reg_1315.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        D_1_reg_359 = C_1_fu_892_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        D_1_reg_359 = C_reg_1321.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        D_2_reg_425 = C_2_fu_983_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        D_2_reg_425 = D_1_reg_359.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        D_3_reg_494 = C_3_fu_1086_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        D_3_reg_494 = D_2_reg_425.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        D_4_reg_562 = C_4_reg_1433.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        D_4_reg_562 = D_3_reg_494.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        E1_reg_338 = E_1_reg_348.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        E1_reg_338 = context_Intermediate_Hash_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        E_1_reg_348 = D_1_reg_359.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        E_1_reg_348 = context_Intermediate_Hash_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        E_2_reg_471 = E_5_reg_482.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        E_2_reg_471 = E_s_reg_402.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        E_3_reg_540 = E_6_reg_550.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        E_3_reg_540 = E_2_reg_471.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        E_4_reg_413 = D_2_reg_425.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        E_4_reg_413 = E_1_reg_348.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        E_5_reg_482 = D_3_reg_494.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        E_5_reg_482 = E_4_reg_413.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        E_6_reg_550 = D_4_reg_562.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        E_6_reg_550 = E_5_reg_482.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        E_s_reg_402 = E_4_reg_413.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        E_s_reg_402 = E1_reg_338.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(exitcond5_fu_623_p2.read(), ap_const_lv1_0))) {
        t_1_reg_326 = ap_const_lv7_10;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        t_1_reg_326 = t_7_fu_791_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        t_2_reg_391 = t_8_reg_1354.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        t_2_reg_391 = ap_const_lv5_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        t_3_reg_460 = t_9_reg_1382.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        t_3_reg_460 = ap_const_lv6_14;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        t_4_reg_529 = t_10_reg_1405.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        t_4_reg_529 = ap_const_lv6_28;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        t_5_reg_596 = t_11_reg_1438.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        t_5_reg_596 = ap_const_lv7_3C;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        t_reg_314 = t_6_reg_1214.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        t_reg_314 = ap_const_lv5_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        A_reg_1299 = context_Intermediate_Hash_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        B_reg_1315 = context_Intermediate_Hash_q0.read();
        C_reg_1321 = context_Intermediate_Hash_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_1094_p2.read()))) {
        C_4_reg_1433 = C_4_fu_1165_p3.read();
        t_11_reg_1438 = t_11_fu_1173_p2.read();
        tmp17_reg_1428 = tmp17_fu_1145_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        D_reg_1339 = context_Intermediate_Hash_q1.read();
        E_reg_1345 = context_Intermediate_Hash_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        W_load_1_reg_1279 = W_q1.read();
        W_load_reg_1274 = W_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        context_Message_Block_load_1_reg_1240 = context_Message_Block_q1.read();
        context_Message_Block_load_reg_1235 = context_Message_Block_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read()))) {
        reg_607 = K_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_991_p2.read()))) {
        t_10_reg_1405 = t_10_fu_1002_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        t_6_reg_1214 = t_6_fu_629_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        t_8_reg_1354 = t_8_fu_803_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_900_p2.read()))) {
        t_9_reg_1382 = t_9_fu_911_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && esl_seteq<1,1,1>(exitcond5_fu_623_p2.read(), ap_const_lv1_0))) {
        tmp_1_reg_1219 = tmp_1_fu_639_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_1094_p2.read()))) {
        tmp_37_reg_1443 = tmp_37_fu_1191_p2.read();
        tmp_38_reg_1448 = tmp_38_fu_1196_p2.read();
        tmp_39_reg_1453 = tmp_39_fu_1201_p2.read();
    }
}

void SHA1ProcessMessageBlock::thread_C_1_fu_892_p3() {
    C_1_fu_892_p3 = esl_concat<2,30>(tmp_27_fu_878_p1.read(), tmp_71_i_i_fu_882_p4.read());
}

void SHA1ProcessMessageBlock::thread_C_2_fu_983_p3() {
    C_2_fu_983_p3 = esl_concat<2,30>(tmp_43_fu_969_p1.read(), tmp_71_i_i1_fu_973_p4.read());
}

void SHA1ProcessMessageBlock::thread_C_3_fu_1086_p3() {
    C_3_fu_1086_p3 = esl_concat<2,30>(tmp_45_fu_1072_p1.read(), tmp_71_i_i2_fu_1076_p4.read());
}

void SHA1ProcessMessageBlock::thread_C_4_fu_1165_p3() {
    C_4_fu_1165_p3 = esl_concat<2,30>(tmp_47_fu_1151_p1.read(), tmp_71_i_i3_fu_1155_p4.read());
}

void SHA1ProcessMessageBlock::thread_K_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read())) {
        K_address0 = ap_const_lv2_3;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        K_address0 = ap_const_lv2_2;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        K_address0 = ap_const_lv2_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        K_address0 = ap_const_lv2_0;
    } else {
        K_address0 = "XX";
    }
}

void SHA1ProcessMessageBlock::thread_K_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()))) {
        K_ce0 = ap_const_logic_1;
    } else {
        K_ce0 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_W_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        W_address0 =  (sc_lv<7>) (tmp_5_fu_683_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read())) {
        W_address0 =  (sc_lv<7>) (tmp_34_fu_997_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        W_address0 =  (sc_lv<7>) (tmp_25_fu_809_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        W_address0 =  (sc_lv<7>) (tmp_17_fu_744_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        W_address0 =  (sc_lv<7>) (tmp_11_fu_711_p1.read());
    } else {
        W_address0 =  (sc_lv<7>) ("XXXXXXX");
    }
}

void SHA1ProcessMessageBlock::thread_W_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        W_address1 =  (sc_lv<7>) (tmp_19_fu_786_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        W_address1 =  (sc_lv<7>) (tmp_41_fu_1134_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        W_address1 =  (sc_lv<7>) (tmp_29_fu_906_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        W_address1 =  (sc_lv<7>) (tmp_15_fu_733_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        W_address1 =  (sc_lv<7>) (tmp_13_fu_722_p1.read());
    } else {
        W_address1 =  (sc_lv<7>) ("XXXXXXX");
    }
}

void SHA1ProcessMessageBlock::thread_W_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()))) {
        W_ce0 = ap_const_logic_1;
    } else {
        W_ce0 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_W_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()))) {
        W_ce1 = ap_const_logic_1;
    } else {
        W_ce1 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_W_d0() {
    W_d0 = esl_concat<24,8>(esl_concat<16,8>(esl_concat<8,8>(context_Message_Block_load_reg_1235.read(), context_Message_Block_load_1_reg_1240.read()), context_Message_Block_q0.read()), context_Message_Block_q1.read());
}

void SHA1ProcessMessageBlock::thread_W_d1() {
    W_d1 = esl_concat<31,1>(tmp_18_fu_765_p1.read(), tmp_20_fu_769_p3.read());
}

void SHA1ProcessMessageBlock::thread_W_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()))) {
        W_we0 = ap_const_logic_1;
    } else {
        W_we0 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_W_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()))) {
        W_we1 = ap_const_logic_1;
    } else {
        W_we1 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_105() {
    ap_sig_105 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(18, 18));
}

void SHA1ProcessMessageBlock::thread_ap_sig_115() {
    ap_sig_115 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void SHA1ProcessMessageBlock::thread_ap_sig_133() {
    ap_sig_133 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void SHA1ProcessMessageBlock::thread_ap_sig_147() {
    ap_sig_147 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void SHA1ProcessMessageBlock::thread_ap_sig_165() {
    ap_sig_165 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void SHA1ProcessMessageBlock::thread_ap_sig_180() {
    ap_sig_180 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void SHA1ProcessMessageBlock::thread_ap_sig_188() {
    ap_sig_188 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void SHA1ProcessMessageBlock::thread_ap_sig_200() {
    ap_sig_200 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void SHA1ProcessMessageBlock::thread_ap_sig_216() {
    ap_sig_216 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void SHA1ProcessMessageBlock::thread_ap_sig_230() {
    ap_sig_230 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(11, 11));
}

void SHA1ProcessMessageBlock::thread_ap_sig_241() {
    ap_sig_241 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(13, 13));
}

void SHA1ProcessMessageBlock::thread_ap_sig_255() {
    ap_sig_255 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(14, 14));
}

void SHA1ProcessMessageBlock::thread_ap_sig_266() {
    ap_sig_266 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(16, 16));
}

void SHA1ProcessMessageBlock::thread_ap_sig_280() {
    ap_sig_280 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(17, 17));
}

void SHA1ProcessMessageBlock::thread_ap_sig_291() {
    ap_sig_291 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(19, 19));
}

void SHA1ProcessMessageBlock::thread_ap_sig_317() {
    ap_sig_317 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(20, 20));
}

void SHA1ProcessMessageBlock::thread_ap_sig_343() {
    ap_sig_343 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void SHA1ProcessMessageBlock::thread_ap_sig_38() {
    ap_sig_38 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void SHA1ProcessMessageBlock::thread_ap_sig_428() {
    ap_sig_428 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(22, 22));
}

void SHA1ProcessMessageBlock::thread_ap_sig_450() {
    ap_sig_450 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(21, 21));
}

void SHA1ProcessMessageBlock::thread_ap_sig_82() {
    ap_sig_82 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void SHA1ProcessMessageBlock::thread_ap_sig_89() {
    ap_sig_89 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(12, 12));
}

void SHA1ProcessMessageBlock::thread_ap_sig_97() {
    ap_sig_97 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(15, 15));
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_82.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_216.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st12_fsm_11() {
    if (ap_sig_230.read()) {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st13_fsm_12() {
    if (ap_sig_89.read()) {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st14_fsm_13() {
    if (ap_sig_241.read()) {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st15_fsm_14() {
    if (ap_sig_255.read()) {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st16_fsm_15() {
    if (ap_sig_97.read()) {
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st17_fsm_16() {
    if (ap_sig_266.read()) {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st18_fsm_17() {
    if (ap_sig_280.read()) {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st19_fsm_18() {
    if (ap_sig_105.read()) {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_38.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st20_fsm_19() {
    if (ap_sig_291.read()) {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st21_fsm_20() {
    if (ap_sig_317.read()) {
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st22_fsm_21() {
    if (ap_sig_450.read()) {
        ap_sig_cseq_ST_st22_fsm_21 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st22_fsm_21 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st23_fsm_22() {
    if (ap_sig_428.read()) {
        ap_sig_cseq_ST_st23_fsm_22 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st23_fsm_22 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_115.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_133.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_343.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_147.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_165.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_180.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_188.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_200.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_context_Intermediate_Hash_addr_1_reg_1305() {
    context_Intermediate_Hash_addr_1_reg_1305 =  (sc_lv<3>) (ap_const_lv64_1);
}

void SHA1ProcessMessageBlock::thread_context_Intermediate_Hash_addr_2_reg_1310() {
    context_Intermediate_Hash_addr_2_reg_1310 =  (sc_lv<3>) (ap_const_lv64_2);
}

void SHA1ProcessMessageBlock::thread_context_Intermediate_Hash_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read())) {
        context_Intermediate_Hash_address0 =  (sc_lv<3>) (ap_const_lv64_3);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        context_Intermediate_Hash_address0 = context_Intermediate_Hash_addr_1_reg_1305.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        context_Intermediate_Hash_address0 =  (sc_lv<3>) (ap_const_lv64_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        context_Intermediate_Hash_address0 =  (sc_lv<3>) (ap_const_lv64_1);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        context_Intermediate_Hash_address0 =  (sc_lv<3>) (ap_const_lv64_0);
    } else {
        context_Intermediate_Hash_address0 =  (sc_lv<3>) ("XXX");
    }
}

void SHA1ProcessMessageBlock::thread_context_Intermediate_Hash_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read())) {
        context_Intermediate_Hash_address1 =  (sc_lv<3>) (ap_const_lv64_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read())) {
        context_Intermediate_Hash_address1 = context_Intermediate_Hash_addr_2_reg_1310.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        context_Intermediate_Hash_address1 =  (sc_lv<3>) (ap_const_lv64_0);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        context_Intermediate_Hash_address1 =  (sc_lv<3>) (ap_const_lv64_3);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        context_Intermediate_Hash_address1 =  (sc_lv<3>) (ap_const_lv64_2);
    } else {
        context_Intermediate_Hash_address1 =  (sc_lv<3>) ("XXX");
    }
}

void SHA1ProcessMessageBlock::thread_context_Intermediate_Hash_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read()))) {
        context_Intermediate_Hash_ce0 = ap_const_logic_1;
    } else {
        context_Intermediate_Hash_ce0 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_context_Intermediate_Hash_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read()))) {
        context_Intermediate_Hash_ce1 = ap_const_logic_1;
    } else {
        context_Intermediate_Hash_ce1 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_context_Intermediate_Hash_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read())) {
        context_Intermediate_Hash_d0 = tmp_38_reg_1448.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        context_Intermediate_Hash_d0 = tmp_36_fu_1185_p2.read();
    } else {
        context_Intermediate_Hash_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void SHA1ProcessMessageBlock::thread_context_Intermediate_Hash_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read())) {
        context_Intermediate_Hash_d1 = tmp_39_reg_1453.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read())) {
        context_Intermediate_Hash_d1 = tmp_37_reg_1443.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        context_Intermediate_Hash_d1 = tmp_35_fu_1179_p2.read();
    } else {
        context_Intermediate_Hash_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void SHA1ProcessMessageBlock::thread_context_Intermediate_Hash_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_1094_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read()))) {
        context_Intermediate_Hash_we0 = ap_const_logic_1;
    } else {
        context_Intermediate_Hash_we0 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_context_Intermediate_Hash_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_1094_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read()))) {
        context_Intermediate_Hash_we1 = ap_const_logic_1;
    } else {
        context_Intermediate_Hash_we1 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_context_Message_Block_Index() {
    context_Message_Block_Index = ap_const_lv16_0;
}

void SHA1ProcessMessageBlock::thread_context_Message_Block_Index_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read())) {
        context_Message_Block_Index_ap_vld = ap_const_logic_1;
    } else {
        context_Message_Block_Index_ap_vld = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_context_Message_Block_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        context_Message_Block_address0 =  (sc_lv<6>) (tmp_3_fu_668_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        context_Message_Block_address0 =  (sc_lv<6>) (tmp_2_fu_647_p1.read());
    } else {
        context_Message_Block_address0 =  (sc_lv<6>) ("XXXXXX");
    }
}

void SHA1ProcessMessageBlock::thread_context_Message_Block_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        context_Message_Block_address1 =  (sc_lv<6>) (tmp_8_fu_678_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        context_Message_Block_address1 =  (sc_lv<6>) (tmp_7_fu_658_p1.read());
    } else {
        context_Message_Block_address1 =  (sc_lv<6>) ("XXXXXX");
    }
}

void SHA1ProcessMessageBlock::thread_context_Message_Block_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()))) {
        context_Message_Block_ce0 = ap_const_logic_1;
    } else {
        context_Message_Block_ce0 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_context_Message_Block_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()))) {
        context_Message_Block_ce1 = ap_const_logic_1;
    } else {
        context_Message_Block_ce1 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_exitcond1_fu_991_p2() {
    exitcond1_fu_991_p2 = (!t_4_reg_529.read().is_01() || !ap_const_lv6_3C.is_01())? sc_lv<1>(): sc_lv<1>(t_4_reg_529.read() == ap_const_lv6_3C);
}

void SHA1ProcessMessageBlock::thread_exitcond2_fu_900_p2() {
    exitcond2_fu_900_p2 = (!t_3_reg_460.read().is_01() || !ap_const_lv6_28.is_01())? sc_lv<1>(): sc_lv<1>(t_3_reg_460.read() == ap_const_lv6_28);
}

void SHA1ProcessMessageBlock::thread_exitcond3_fu_797_p2() {
    exitcond3_fu_797_p2 = (!t_2_reg_391.read().is_01() || !ap_const_lv5_14.is_01())? sc_lv<1>(): sc_lv<1>(t_2_reg_391.read() == ap_const_lv5_14);
}

void SHA1ProcessMessageBlock::thread_exitcond4_fu_699_p2() {
    exitcond4_fu_699_p2 = (!t_1_reg_326.read().is_01() || !ap_const_lv7_50.is_01())? sc_lv<1>(): sc_lv<1>(t_1_reg_326.read() == ap_const_lv7_50);
}

void SHA1ProcessMessageBlock::thread_exitcond5_fu_623_p2() {
    exitcond5_fu_623_p2 = (!t_reg_314.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(t_reg_314.read() == ap_const_lv5_10);
}

void SHA1ProcessMessageBlock::thread_exitcond_fu_1094_p2() {
    exitcond_fu_1094_p2 = (!t_5_reg_596.read().is_01() || !ap_const_lv7_50.is_01())? sc_lv<1>(): sc_lv<1>(t_5_reg_596.read() == ap_const_lv7_50);
}

void SHA1ProcessMessageBlock::thread_grp_fu_611_p2() {
    grp_fu_611_p2 = (!reg_607.read().is_01() || !W_q0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(reg_607.read()) + sc_biguint<32>(W_q0.read()));
}

void SHA1ProcessMessageBlock::thread_grp_fu_617_p2() {
    grp_fu_617_p2 = (!reg_607.read().is_01() || !W_q1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(reg_607.read()) + sc_biguint<32>(W_q1.read()));
}

void SHA1ProcessMessageBlock::thread_t_10_fu_1002_p2() {
    t_10_fu_1002_p2 = (!ap_const_lv6_1.is_01() || !t_4_reg_529.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_1) + sc_biguint<6>(t_4_reg_529.read()));
}

void SHA1ProcessMessageBlock::thread_t_11_fu_1173_p2() {
    t_11_fu_1173_p2 = (!ap_const_lv7_1.is_01() || !t_5_reg_596.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_1) + sc_biguint<7>(t_5_reg_596.read()));
}

void SHA1ProcessMessageBlock::thread_t_6_fu_629_p2() {
    t_6_fu_629_p2 = (!t_reg_314.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(t_reg_314.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void SHA1ProcessMessageBlock::thread_t_7_fu_791_p2() {
    t_7_fu_791_p2 = (!ap_const_lv7_1.is_01() || !t_1_reg_326.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_1) + sc_biguint<7>(t_1_reg_326.read()));
}

void SHA1ProcessMessageBlock::thread_t_8_fu_803_p2() {
    t_8_fu_803_p2 = (!t_2_reg_391.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(t_2_reg_391.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void SHA1ProcessMessageBlock::thread_t_9_fu_911_p2() {
    t_9_fu_911_p2 = (!ap_const_lv6_1.is_01() || !t_3_reg_460.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_1) + sc_biguint<6>(t_3_reg_460.read()));
}

void SHA1ProcessMessageBlock::thread_temp_1_fu_963_p2() {
    temp_1_fu_963_p2 = (!tmp10_fu_957_p2.read().is_01() || !grp_fu_617_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp10_fu_957_p2.read()) + sc_biguint<32>(grp_fu_617_p2.read()));
}

void SHA1ProcessMessageBlock::thread_temp_2_fu_1066_p2() {
    temp_2_fu_1066_p2 = (!tmp13_fu_1060_p2.read().is_01() || !grp_fu_611_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp13_fu_1060_p2.read()) + sc_biguint<32>(grp_fu_611_p2.read()));
}

void SHA1ProcessMessageBlock::thread_temp_3_fu_1206_p2() {
    temp_3_fu_1206_p2 = (!tmp17_reg_1428.read().is_01() || !grp_fu_617_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp17_reg_1428.read()) + sc_biguint<32>(grp_fu_617_p2.read()));
}

void SHA1ProcessMessageBlock::thread_temp_fu_872_p2() {
    temp_fu_872_p2 = (!tmp6_fu_866_p2.read().is_01() || !grp_fu_611_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp6_fu_866_p2.read()) + sc_biguint<32>(grp_fu_611_p2.read()));
}

void SHA1ProcessMessageBlock::thread_tmp10_fu_957_p2() {
    tmp10_fu_957_p2 = (!tmp11_fu_951_p2.read().is_01() || !tmp_72_i2_fu_931_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp11_fu_951_p2.read()) + sc_biguint<32>(tmp_72_i2_fu_931_p3.read()));
}

void SHA1ProcessMessageBlock::thread_tmp11_fu_951_p2() {
    tmp11_fu_951_p2 = (!tmp_28_fu_945_p2.read().is_01() || !E_s_reg_402.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_28_fu_945_p2.read()) + sc_biguint<32>(E_s_reg_402.read()));
}

void SHA1ProcessMessageBlock::thread_tmp13_fu_1060_p2() {
    tmp13_fu_1060_p2 = (!tmp14_fu_1054_p2.read().is_01() || !tmp_72_i3_fu_1022_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp14_fu_1054_p2.read()) + sc_biguint<32>(tmp_72_i3_fu_1022_p3.read()));
}

void SHA1ProcessMessageBlock::thread_tmp14_fu_1054_p2() {
    tmp14_fu_1054_p2 = (!E_2_reg_471.read().is_01() || !tmp_33_fu_1048_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(E_2_reg_471.read()) + sc_biguint<32>(tmp_33_fu_1048_p2.read()));
}

void SHA1ProcessMessageBlock::thread_tmp15_fu_1122_p2() {
    tmp15_fu_1122_p2 = (B_read_assign_3_reg_574.read() ^ E_6_reg_550.read());
}

void SHA1ProcessMessageBlock::thread_tmp17_fu_1145_p2() {
    tmp17_fu_1145_p2 = (!tmp18_fu_1139_p2.read().is_01() || !tmp_72_i4_fu_1114_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp18_fu_1139_p2.read()) + sc_biguint<32>(tmp_72_i4_fu_1114_p3.read()));
}

void SHA1ProcessMessageBlock::thread_tmp18_fu_1139_p2() {
    tmp18_fu_1139_p2 = (!tmp_40_fu_1128_p2.read().is_01() || !E_3_reg_540.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_40_fu_1128_p2.read()) + sc_biguint<32>(E_3_reg_540.read()));
}

void SHA1ProcessMessageBlock::thread_tmp3_fu_749_p2() {
    tmp3_fu_749_p2 = (W_load_reg_1274.read() ^ W_q1.read());
}

void SHA1ProcessMessageBlock::thread_tmp4_fu_754_p2() {
    tmp4_fu_754_p2 = (W_load_1_reg_1279.read() ^ W_q0.read());
}

void SHA1ProcessMessageBlock::thread_tmp6_fu_866_p2() {
    tmp6_fu_866_p2 = (!tmp7_fu_860_p2.read().is_01() || !tmp_72_i1_fu_828_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp7_fu_860_p2.read()) + sc_biguint<32>(tmp_72_i1_fu_828_p3.read()));
}

void SHA1ProcessMessageBlock::thread_tmp7_fu_860_p2() {
    tmp7_fu_860_p2 = (!E1_reg_338.read().is_01() || !tmp_24_fu_854_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(E1_reg_338.read()) + sc_biguint<32>(tmp_24_fu_854_p2.read()));
}

void SHA1ProcessMessageBlock::thread_tmp8_fu_939_p2() {
    tmp8_fu_939_p2 = (B_read_assign_1_reg_437.read() ^ E_4_reg_413.read());
}

void SHA1ProcessMessageBlock::thread_tmp_10_fu_705_p2() {
    tmp_10_fu_705_p2 = (!ap_const_lv7_7D.is_01() || !t_1_reg_326.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_7D) + sc_biguint<7>(t_1_reg_326.read()));
}

void SHA1ProcessMessageBlock::thread_tmp_11_fu_711_p1() {
    tmp_11_fu_711_p1 = esl_zext<64,7>(tmp_10_fu_705_p2.read());
}

void SHA1ProcessMessageBlock::thread_tmp_12_fu_716_p2() {
    tmp_12_fu_716_p2 = (!ap_const_lv7_78.is_01() || !t_1_reg_326.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_78) + sc_biguint<7>(t_1_reg_326.read()));
}

void SHA1ProcessMessageBlock::thread_tmp_13_fu_722_p1() {
    tmp_13_fu_722_p1 = esl_zext<64,7>(tmp_12_fu_716_p2.read());
}

void SHA1ProcessMessageBlock::thread_tmp_14_fu_727_p2() {
    tmp_14_fu_727_p2 = (!ap_const_lv7_72.is_01() || !t_1_reg_326.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_72) + sc_biguint<7>(t_1_reg_326.read()));
}

void SHA1ProcessMessageBlock::thread_tmp_15_fu_733_p1() {
    tmp_15_fu_733_p1 = esl_zext<64,7>(tmp_14_fu_727_p2.read());
}

void SHA1ProcessMessageBlock::thread_tmp_16_fu_738_p2() {
    tmp_16_fu_738_p2 = (!ap_const_lv7_70.is_01() || !t_1_reg_326.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_70) + sc_biguint<7>(t_1_reg_326.read()));
}

void SHA1ProcessMessageBlock::thread_tmp_17_fu_744_p1() {
    tmp_17_fu_744_p1 = esl_zext<64,7>(tmp_16_fu_738_p2.read());
}

void SHA1ProcessMessageBlock::thread_tmp_18_fu_765_p1() {
    tmp_18_fu_765_p1 = word_assign_fu_759_p2.read().range(31-1, 0);
}

void SHA1ProcessMessageBlock::thread_tmp_19_fu_786_p1() {
    tmp_19_fu_786_p1 = esl_zext<64,7>(t_1_reg_326.read());
}

void SHA1ProcessMessageBlock::thread_tmp_1_fu_639_p3() {
    tmp_1_fu_639_p3 = esl_concat<4,2>(tmp_fu_635_p1.read(), ap_const_lv2_0);
}

void SHA1ProcessMessageBlock::thread_tmp_20_fu_769_p3() {
    tmp_20_fu_769_p3 = word_assign_fu_759_p2.read().range(31, 31);
}

void SHA1ProcessMessageBlock::thread_tmp_21_fu_836_p2() {
    tmp_21_fu_836_p2 = (D_1_reg_359.read() & B_read_assign_reg_370.read());
}

void SHA1ProcessMessageBlock::thread_tmp_22_fu_842_p2() {
    tmp_22_fu_842_p2 = (B_read_assign_reg_370.read() ^ ap_const_lv32_FFFFFFFF);
}

void SHA1ProcessMessageBlock::thread_tmp_23_fu_848_p2() {
    tmp_23_fu_848_p2 = (E_1_reg_348.read() & tmp_22_fu_842_p2.read());
}

void SHA1ProcessMessageBlock::thread_tmp_24_fu_854_p2() {
    tmp_24_fu_854_p2 = (tmp_23_fu_848_p2.read() | tmp_21_fu_836_p2.read());
}

void SHA1ProcessMessageBlock::thread_tmp_25_fu_809_p1() {
    tmp_25_fu_809_p1 = esl_zext<64,5>(t_2_reg_391.read());
}

void SHA1ProcessMessageBlock::thread_tmp_26_fu_814_p1() {
    tmp_26_fu_814_p1 = B_1_reg_380.read().range(27-1, 0);
}

void SHA1ProcessMessageBlock::thread_tmp_27_fu_878_p1() {
    tmp_27_fu_878_p1 = B_read_assign_reg_370.read().range(2-1, 0);
}

void SHA1ProcessMessageBlock::thread_tmp_28_fu_945_p2() {
    tmp_28_fu_945_p2 = (tmp8_fu_939_p2.read() ^ D_2_reg_425.read());
}

void SHA1ProcessMessageBlock::thread_tmp_29_fu_906_p1() {
    tmp_29_fu_906_p1 = esl_zext<64,6>(t_3_reg_460.read());
}

void SHA1ProcessMessageBlock::thread_tmp_2_fu_647_p1() {
    tmp_2_fu_647_p1 = esl_zext<64,6>(tmp_1_fu_639_p3.read());
}

void SHA1ProcessMessageBlock::thread_tmp_30_fu_1030_p2() {
    tmp_30_fu_1030_p2 = (E_5_reg_482.read() | D_3_reg_494.read());
}

void SHA1ProcessMessageBlock::thread_tmp_31_fu_1036_p2() {
    tmp_31_fu_1036_p2 = (tmp_30_fu_1030_p2.read() & B_read_assign_2_reg_506.read());
}

void SHA1ProcessMessageBlock::thread_tmp_32_fu_1042_p2() {
    tmp_32_fu_1042_p2 = (E_5_reg_482.read() & D_3_reg_494.read());
}

void SHA1ProcessMessageBlock::thread_tmp_33_fu_1048_p2() {
    tmp_33_fu_1048_p2 = (tmp_31_fu_1036_p2.read() | tmp_32_fu_1042_p2.read());
}

void SHA1ProcessMessageBlock::thread_tmp_34_fu_997_p1() {
    tmp_34_fu_997_p1 = esl_zext<64,6>(t_4_reg_529.read());
}

void SHA1ProcessMessageBlock::thread_tmp_35_fu_1179_p2() {
    tmp_35_fu_1179_p2 = (!A_reg_1299.read().is_01() || !B_4_reg_584.read().is_01())? sc_lv<32>(): (sc_biguint<32>(A_reg_1299.read()) + sc_biguint<32>(B_4_reg_584.read()));
}

void SHA1ProcessMessageBlock::thread_tmp_36_fu_1185_p2() {
    tmp_36_fu_1185_p2 = (!B_reg_1315.read().is_01() || !B_read_assign_3_reg_574.read().is_01())? sc_lv<32>(): (sc_biguint<32>(B_reg_1315.read()) + sc_biguint<32>(B_read_assign_3_reg_574.read()));
}

void SHA1ProcessMessageBlock::thread_tmp_37_fu_1191_p2() {
    tmp_37_fu_1191_p2 = (!C_reg_1321.read().is_01() || !D_4_reg_562.read().is_01())? sc_lv<32>(): (sc_biguint<32>(C_reg_1321.read()) + sc_biguint<32>(D_4_reg_562.read()));
}

void SHA1ProcessMessageBlock::thread_tmp_38_fu_1196_p2() {
    tmp_38_fu_1196_p2 = (!D_reg_1339.read().is_01() || !E_6_reg_550.read().is_01())? sc_lv<32>(): (sc_biguint<32>(D_reg_1339.read()) + sc_biguint<32>(E_6_reg_550.read()));
}

void SHA1ProcessMessageBlock::thread_tmp_39_fu_1201_p2() {
    tmp_39_fu_1201_p2 = (!E_reg_1345.read().is_01() || !E_3_reg_540.read().is_01())? sc_lv<32>(): (sc_biguint<32>(E_reg_1345.read()) + sc_biguint<32>(E_3_reg_540.read()));
}

void SHA1ProcessMessageBlock::thread_tmp_3_fu_668_p1() {
    tmp_3_fu_668_p1 = esl_zext<64,6>(tmp_s_fu_663_p2.read());
}

void SHA1ProcessMessageBlock::thread_tmp_40_fu_1128_p2() {
    tmp_40_fu_1128_p2 = (tmp15_fu_1122_p2.read() ^ D_4_reg_562.read());
}

void SHA1ProcessMessageBlock::thread_tmp_41_fu_1134_p1() {
    tmp_41_fu_1134_p1 = esl_zext<64,7>(t_5_reg_596.read());
}

void SHA1ProcessMessageBlock::thread_tmp_42_fu_917_p1() {
    tmp_42_fu_917_p1 = B_2_reg_448.read().range(27-1, 0);
}

void SHA1ProcessMessageBlock::thread_tmp_43_fu_969_p1() {
    tmp_43_fu_969_p1 = B_read_assign_1_reg_437.read().range(2-1, 0);
}

void SHA1ProcessMessageBlock::thread_tmp_44_fu_1008_p1() {
    tmp_44_fu_1008_p1 = B_3_reg_517.read().range(27-1, 0);
}

void SHA1ProcessMessageBlock::thread_tmp_45_fu_1072_p1() {
    tmp_45_fu_1072_p1 = B_read_assign_2_reg_506.read().range(2-1, 0);
}

void SHA1ProcessMessageBlock::thread_tmp_46_fu_1100_p1() {
    tmp_46_fu_1100_p1 = B_4_reg_584.read().range(27-1, 0);
}

void SHA1ProcessMessageBlock::thread_tmp_47_fu_1151_p1() {
    tmp_47_fu_1151_p1 = B_read_assign_3_reg_574.read().range(2-1, 0);
}

void SHA1ProcessMessageBlock::thread_tmp_4_fu_673_p2() {
    tmp_4_fu_673_p2 = (tmp_1_reg_1219.read() | ap_const_lv6_3);
}

void SHA1ProcessMessageBlock::thread_tmp_5_fu_683_p1() {
    tmp_5_fu_683_p1 = esl_zext<64,5>(t_reg_314.read());
}

void SHA1ProcessMessageBlock::thread_tmp_6_fu_652_p2() {
    tmp_6_fu_652_p2 = (tmp_1_fu_639_p3.read() | ap_const_lv6_1);
}

void SHA1ProcessMessageBlock::thread_tmp_71_i1_fu_818_p4() {
    tmp_71_i1_fu_818_p4 = B_1_reg_380.read().range(31, 27);
}

void SHA1ProcessMessageBlock::thread_tmp_71_i2_fu_921_p4() {
    tmp_71_i2_fu_921_p4 = B_2_reg_448.read().range(31, 27);
}

void SHA1ProcessMessageBlock::thread_tmp_71_i3_fu_1012_p4() {
    tmp_71_i3_fu_1012_p4 = B_3_reg_517.read().range(31, 27);
}

void SHA1ProcessMessageBlock::thread_tmp_71_i4_fu_1104_p4() {
    tmp_71_i4_fu_1104_p4 = B_4_reg_584.read().range(31, 27);
}

void SHA1ProcessMessageBlock::thread_tmp_71_i_i1_fu_973_p4() {
    tmp_71_i_i1_fu_973_p4 = B_read_assign_1_reg_437.read().range(31, 2);
}

void SHA1ProcessMessageBlock::thread_tmp_71_i_i2_fu_1076_p4() {
    tmp_71_i_i2_fu_1076_p4 = B_read_assign_2_reg_506.read().range(31, 2);
}

void SHA1ProcessMessageBlock::thread_tmp_71_i_i3_fu_1155_p4() {
    tmp_71_i_i3_fu_1155_p4 = B_read_assign_3_reg_574.read().range(31, 2);
}

void SHA1ProcessMessageBlock::thread_tmp_71_i_i_fu_882_p4() {
    tmp_71_i_i_fu_882_p4 = B_read_assign_reg_370.read().range(31, 2);
}

void SHA1ProcessMessageBlock::thread_tmp_72_i1_fu_828_p3() {
    tmp_72_i1_fu_828_p3 = esl_concat<27,5>(tmp_26_fu_814_p1.read(), tmp_71_i1_fu_818_p4.read());
}

void SHA1ProcessMessageBlock::thread_tmp_72_i2_fu_931_p3() {
    tmp_72_i2_fu_931_p3 = esl_concat<27,5>(tmp_42_fu_917_p1.read(), tmp_71_i2_fu_921_p4.read());
}

void SHA1ProcessMessageBlock::thread_tmp_72_i3_fu_1022_p3() {
    tmp_72_i3_fu_1022_p3 = esl_concat<27,5>(tmp_44_fu_1008_p1.read(), tmp_71_i3_fu_1012_p4.read());
}

void SHA1ProcessMessageBlock::thread_tmp_72_i4_fu_1114_p3() {
    tmp_72_i4_fu_1114_p3 = esl_concat<27,5>(tmp_46_fu_1100_p1.read(), tmp_71_i4_fu_1104_p4.read());
}

void SHA1ProcessMessageBlock::thread_tmp_7_fu_658_p1() {
    tmp_7_fu_658_p1 = esl_zext<64,6>(tmp_6_fu_652_p2.read());
}

void SHA1ProcessMessageBlock::thread_tmp_8_fu_678_p1() {
    tmp_8_fu_678_p1 = esl_zext<64,6>(tmp_4_fu_673_p2.read());
}

void SHA1ProcessMessageBlock::thread_tmp_fu_635_p1() {
    tmp_fu_635_p1 = t_reg_314.read().range(4-1, 0);
}

void SHA1ProcessMessageBlock::thread_tmp_s_fu_663_p2() {
    tmp_s_fu_663_p2 = (tmp_1_reg_1219.read() | ap_const_lv6_2);
}

void SHA1ProcessMessageBlock::thread_word_assign_fu_759_p2() {
    word_assign_fu_759_p2 = (tmp4_fu_754_p2.read() ^ tmp3_fu_749_p2.read());
}

void SHA1ProcessMessageBlock::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(exitcond5_fu_623_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        case 16 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_699_p2.read())) {
                ap_NS_fsm = ap_ST_st8_fsm_7;
            } else {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 1024 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_797_p2.read())) {
                ap_NS_fsm = ap_ST_st13_fsm_12;
            } else {
                ap_NS_fsm = ap_ST_st12_fsm_11;
            }
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 8192 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_900_p2.read())) {
                ap_NS_fsm = ap_ST_st16_fsm_15;
            } else {
                ap_NS_fsm = ap_ST_st15_fsm_14;
            }
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
            break;
        case 65536 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_991_p2.read())) {
                ap_NS_fsm = ap_ST_st19_fsm_18;
            } else {
                ap_NS_fsm = ap_ST_st18_fsm_17;
            }
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_st20_fsm_19;
            break;
        case 524288 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_1094_p2.read())) {
                ap_NS_fsm = ap_ST_st22_fsm_21;
            } else {
                ap_NS_fsm = ap_ST_st21_fsm_20;
            }
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_st20_fsm_19;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_st23_fsm_22;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<23>) ("XXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void SHA1ProcessMessageBlock::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Intermediate_Hash_address0\" :  \"" << context_Intermediate_Hash_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Intermediate_Hash_ce0\" :  \"" << context_Intermediate_Hash_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Intermediate_Hash_we0\" :  \"" << context_Intermediate_Hash_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Intermediate_Hash_d0\" :  \"" << context_Intermediate_Hash_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"context_Intermediate_Hash_q0\" :  \"" << context_Intermediate_Hash_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Intermediate_Hash_address1\" :  \"" << context_Intermediate_Hash_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Intermediate_Hash_ce1\" :  \"" << context_Intermediate_Hash_ce1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Intermediate_Hash_we1\" :  \"" << context_Intermediate_Hash_we1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Intermediate_Hash_d1\" :  \"" << context_Intermediate_Hash_d1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"context_Intermediate_Hash_q1\" :  \"" << context_Intermediate_Hash_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Message_Block_Index\" :  \"" << context_Message_Block_Index.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Message_Block_Index_ap_vld\" :  \"" << context_Message_Block_Index_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Message_Block_address0\" :  \"" << context_Message_Block_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Message_Block_ce0\" :  \"" << context_Message_Block_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"context_Message_Block_q0\" :  \"" << context_Message_Block_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Message_Block_address1\" :  \"" << context_Message_Block_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Message_Block_ce1\" :  \"" << context_Message_Block_ce1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"context_Message_Block_q1\" :  \"" << context_Message_Block_q1.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

