-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.1
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity SHA1ProcessMessageBlock_SHA1CircularShift is
port (
    bits : IN STD_LOGIC_VECTOR (4 downto 0);
    word : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of SHA1ProcessMessageBlock_SHA1CircularShift is 
    constant ap_true : BOOLEAN := true;
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal tmp_fu_22_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_cast_fu_26_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_63_fu_36_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_63_cast_fu_42_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_64_fu_46_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_30_p2 : STD_LOGIC_VECTOR (31 downto 0);


begin



    ap_return <= (tmp_64_fu_46_p2 or tmp_s_fu_30_p2);
    tmp_63_cast_fu_42_p1 <= std_logic_vector(resize(unsigned(tmp_63_fu_36_p2),32));
    tmp_63_fu_36_p2 <= std_logic_vector(signed(ap_const_lv6_20) - signed(tmp_cast_fu_26_p1));
    tmp_64_fu_46_p2 <= std_logic_vector(shift_right(unsigned(word),to_integer(unsigned('0' & tmp_63_cast_fu_42_p1(31-1 downto 0)))));
    tmp_cast_fu_26_p1 <= std_logic_vector(resize(unsigned(bits),6));
    tmp_fu_22_p1 <= std_logic_vector(resize(unsigned(bits),32));
    tmp_s_fu_30_p2 <= std_logic_vector(shift_left(unsigned(word),to_integer(unsigned('0' & tmp_fu_22_p1(31-1 downto 0)))));
end behav;
