#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("context_Intermediate_Hash_address0", 3, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("context_Intermediate_Hash_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("context_Intermediate_Hash_we0", 1, hls_out, 0, "ap_memory", "mem_we", 1),
	Port_Property("context_Intermediate_Hash_d0", 32, hls_out, 0, "ap_memory", "mem_din", 1),
	Port_Property("context_Intermediate_Hash_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("context_Intermediate_Hash_address1", 3, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("context_Intermediate_Hash_ce1", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("context_Intermediate_Hash_we1", 1, hls_out, 0, "ap_memory", "mem_we", 1),
	Port_Property("context_Intermediate_Hash_d1", 32, hls_out, 0, "ap_memory", "mem_din", 1),
	Port_Property("context_Intermediate_Hash_q1", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("context_Message_Block_Index", 16, hls_out, 1, "ap_vld", "out_data", 1),
	Port_Property("context_Message_Block_Index_ap_vld", 1, hls_out, 1, "ap_vld", "out_vld", 1),
	Port_Property("context_Message_Block_address0", 6, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("context_Message_Block_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("context_Message_Block_q0", 8, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("context_Message_Block_address1", 6, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("context_Message_Block_ce1", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("context_Message_Block_q1", 8, hls_in, 2, "ap_memory", "mem_dout", 1),
};
const char* HLS_Design_Meta::dut_name = "SHA1ProcessMessageBlock";
