lappend pragmaStatus0 {pragma "DATA_PACK" source "/home/matt/workspace/sha1_hls/sha1.c" location "SHA1ProcessMessageBlock" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "context"}
lappend pragmaStatus1 {pragma "UNROLL" source "/home/matt/workspace/sha1_hls/sha1.c" location "SHA1ProcessMessageBlock/loop1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "UNROLL" source "/home/matt/workspace/sha1_hls/sha1.c" location "SHA1ProcessMessageBlock/loop5" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "UNROLL" source "/home/matt/workspace/sha1_hls/sha1.c" location "SHA1ProcessMessageBlock/loop4" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "UNROLL" source "/home/matt/workspace/sha1_hls/sha1.c" location "SHA1ProcessMessageBlock/loop2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "UNROLL" source "/home/matt/workspace/sha1_hls/sha1.c" location "SHA1ProcessMessageBlock/loop3" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "UNROLL" source "/home/matt/workspace/sha1_hls/sha1.c" location "SHA1ProcessMessageBlock/loop6" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "ARRAY_PARTITION" source "/home/matt/workspace/sha1_hls/sha1.c" location "SHA1ProcessMessageBlock" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "W"}
lappend pragmaStatus0 {pragma "DATA_PACK" source "/home/matt/workspace/sha1_hls/sha1_original.c" location "SHA1ProcessMessageBlock" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATA_PACK' cannot be applied: Function 'SHA1ProcessMessageBlock' does not exist in any synthesis source file." variable "context"}
lappend pragmaStatus1 {pragma "UNROLL" source "/home/matt/workspace/sha1_hls/sha1_original.c" location "SHA1ProcessMessageBlock/loop1" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'SHA1ProcessMessageBlock' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "UNROLL" source "/home/matt/workspace/sha1_hls/sha1_original.c" location "SHA1ProcessMessageBlock/loop5" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'SHA1ProcessMessageBlock' does not exist in any synthesis source file."}
lappend pragmaStatus3 {pragma "UNROLL" source "/home/matt/workspace/sha1_hls/sha1_original.c" location "SHA1ProcessMessageBlock/loop4" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'SHA1ProcessMessageBlock' does not exist in any synthesis source file."}
lappend pragmaStatus4 {pragma "UNROLL" source "/home/matt/workspace/sha1_hls/sha1_original.c" location "SHA1ProcessMessageBlock/loop2" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'SHA1ProcessMessageBlock' does not exist in any synthesis source file."}
lappend pragmaStatus5 {pragma "UNROLL" source "/home/matt/workspace/sha1_hls/sha1_original.c" location "SHA1ProcessMessageBlock/loop3" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'SHA1ProcessMessageBlock' does not exist in any synthesis source file."}
lappend pragmaStatus6 {pragma "UNROLL" source "/home/matt/workspace/sha1_hls/sha1_original.c" location "SHA1ProcessMessageBlock/loop6" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'SHA1ProcessMessageBlock' does not exist in any synthesis source file."}
lappend pragmaStatus7 {pragma "ARRAY_PARTITION" source "/home/matt/workspace/sha1_hls/sha1_original.c" location "SHA1ProcessMessageBlock" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'SHA1ProcessMessageBlock' does not exist in any synthesis source file." variable "W"}
