// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "SHA1ProcessMessageBlock.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic SHA1ProcessMessageBlock::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic SHA1ProcessMessageBlock::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<20> SHA1ProcessMessageBlock::ap_ST_st1_fsm_0 = "1";
const sc_lv<20> SHA1ProcessMessageBlock::ap_ST_st2_fsm_1 = "10";
const sc_lv<20> SHA1ProcessMessageBlock::ap_ST_st3_fsm_2 = "100";
const sc_lv<20> SHA1ProcessMessageBlock::ap_ST_st4_fsm_3 = "1000";
const sc_lv<20> SHA1ProcessMessageBlock::ap_ST_st5_fsm_4 = "10000";
const sc_lv<20> SHA1ProcessMessageBlock::ap_ST_st6_fsm_5 = "100000";
const sc_lv<20> SHA1ProcessMessageBlock::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<20> SHA1ProcessMessageBlock::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<20> SHA1ProcessMessageBlock::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<20> SHA1ProcessMessageBlock::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<20> SHA1ProcessMessageBlock::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<20> SHA1ProcessMessageBlock::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<20> SHA1ProcessMessageBlock::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<20> SHA1ProcessMessageBlock::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<20> SHA1ProcessMessageBlock::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<20> SHA1ProcessMessageBlock::ap_ST_st16_fsm_15 = "1000000000000000";
const sc_lv<20> SHA1ProcessMessageBlock::ap_ST_st17_fsm_16 = "10000000000000000";
const sc_lv<20> SHA1ProcessMessageBlock::ap_ST_st18_fsm_17 = "100000000000000000";
const sc_lv<20> SHA1ProcessMessageBlock::ap_ST_st19_fsm_18 = "1000000000000000000";
const sc_lv<20> SHA1ProcessMessageBlock::ap_ST_st20_fsm_19 = "10000000000000000000";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> SHA1ProcessMessageBlock::ap_const_lv1_1 = "1";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_1 = "1";
const sc_lv<1> SHA1ProcessMessageBlock::ap_const_lv1_0 = "0";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_2 = "10";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_4 = "100";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_5 = "101";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_6 = "110";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_7 = "111";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_8 = "1000";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_9 = "1001";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_A = "1010";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_B = "1011";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_C = "1100";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_D = "1101";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_E = "1110";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_F = "1111";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_10 = "10000";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_11 = "10001";
const sc_lv<5> SHA1ProcessMessageBlock::ap_const_lv5_0 = "00000";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_3 = "11";
const sc_lv<7> SHA1ProcessMessageBlock::ap_const_lv7_10 = "10000";
const sc_lv<6> SHA1ProcessMessageBlock::ap_const_lv6_14 = "10100";
const sc_lv<6> SHA1ProcessMessageBlock::ap_const_lv6_28 = "101000";
const sc_lv<7> SHA1ProcessMessageBlock::ap_const_lv7_3C = "111100";
const sc_lv<64> SHA1ProcessMessageBlock::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> SHA1ProcessMessageBlock::ap_const_lv64_1 = "1";
const sc_lv<64> SHA1ProcessMessageBlock::ap_const_lv64_2 = "10";
const sc_lv<64> SHA1ProcessMessageBlock::ap_const_lv64_3 = "11";
const sc_lv<64> SHA1ProcessMessageBlock::ap_const_lv64_4 = "100";
const sc_lv<16> SHA1ProcessMessageBlock::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_13 = "10011";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_12 = "10010";
const sc_lv<5> SHA1ProcessMessageBlock::ap_const_lv5_10 = "10000";
const sc_lv<5> SHA1ProcessMessageBlock::ap_const_lv5_1 = "1";
const sc_lv<2> SHA1ProcessMessageBlock::ap_const_lv2_0 = "00";
const sc_lv<6> SHA1ProcessMessageBlock::ap_const_lv6_1 = "1";
const sc_lv<6> SHA1ProcessMessageBlock::ap_const_lv6_2 = "10";
const sc_lv<6> SHA1ProcessMessageBlock::ap_const_lv6_3 = "11";
const sc_lv<7> SHA1ProcessMessageBlock::ap_const_lv7_50 = "1010000";
const sc_lv<7> SHA1ProcessMessageBlock::ap_const_lv7_7D = "1111101";
const sc_lv<7> SHA1ProcessMessageBlock::ap_const_lv7_78 = "1111000";
const sc_lv<7> SHA1ProcessMessageBlock::ap_const_lv7_72 = "1110010";
const sc_lv<7> SHA1ProcessMessageBlock::ap_const_lv7_70 = "1110000";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_1F = "11111";
const sc_lv<7> SHA1ProcessMessageBlock::ap_const_lv7_1 = "1";
const sc_lv<5> SHA1ProcessMessageBlock::ap_const_lv5_14 = "10100";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_1B = "11011";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_5A827999 = "1011010100000100111100110011001";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_6ED9EBA1 = "1101110110110011110101110100001";
const sc_lv<6> SHA1ProcessMessageBlock::ap_const_lv6_3C = "111100";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_8F1BBCDC = "10001111000110111011110011011100";
const sc_lv<32> SHA1ProcessMessageBlock::ap_const_lv32_CA62C1D6 = "11001010011000101100000111010110";

SHA1ProcessMessageBlock::SHA1ProcessMessageBlock(sc_module_name name) : sc_module(name), mVcdFile(0) {
    W_U = new SHA1ProcessMessageBlock_W("W_U");
    W_U->clk(ap_clk);
    W_U->reset(ap_rst);
    W_U->address0(W_address0);
    W_U->ce0(W_ce0);
    W_U->we0(W_we0);
    W_U->d0(W_d0);
    W_U->q0(W_q0);
    W_U->address1(W_address1);
    W_U->ce1(W_ce1);
    W_U->we1(W_we1);
    W_U->d1(W_d1);
    W_U->q1(W_q1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_C_1_fu_866_p3);
    sensitive << ( tmp_27_fu_852_p1 );
    sensitive << ( tmp_71_i_i_fu_856_p4 );

    SC_METHOD(thread_C_2_fu_963_p3);
    sensitive << ( tmp_43_fu_949_p1 );
    sensitive << ( tmp_71_i_i1_fu_953_p4 );

    SC_METHOD(thread_C_3_fu_1072_p3);
    sensitive << ( tmp_45_fu_1058_p1 );
    sensitive << ( tmp_71_i_i2_fu_1062_p4 );

    SC_METHOD(thread_C_4_fu_1129_p3);
    sensitive << ( tmp_47_fu_1115_p1 );
    sensitive << ( tmp_71_i_i3_fu_1119_p4 );

    SC_METHOD(thread_W_address0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_5_fu_651_p1 );
    sensitive << ( tmp_11_fu_679_p1 );
    sensitive << ( tmp_17_fu_712_p1 );
    sensitive << ( tmp_25_fu_777_p1 );
    sensitive << ( tmp_34_fu_977_p1 );

    SC_METHOD(thread_W_address1);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( tmp_13_fu_690_p1 );
    sensitive << ( tmp_15_fu_701_p1 );
    sensitive << ( tmp_19_fu_754_p1 );
    sensitive << ( tmp_29_fu_880_p1 );
    sensitive << ( tmp_41_fu_1098_p1 );

    SC_METHOD(thread_W_ce0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_W_ce1);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );

    SC_METHOD(thread_W_d0);
    sensitive << ( context_Message_Block_q0 );
    sensitive << ( context_Message_Block_q1 );
    sensitive << ( context_Message_Block_load_reg_1227 );
    sensitive << ( context_Message_Block_load_1_reg_1232 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_W_d1);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( tmp_18_fu_733_p1 );
    sensitive << ( tmp_20_fu_737_p3 );

    SC_METHOD(thread_W_we0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_W_we1);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );

    SC_METHOD(thread_ap_sig_105);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_123);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_138);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_146);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_158);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_171);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_181);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_195);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_206);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_220);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_231);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_245);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_256);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_282);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_308);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_35);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_399);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_421);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_73);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_91);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_171 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_181 );

    SC_METHOD(thread_ap_sig_cseq_ST_st12_fsm_11);
    sensitive << ( ap_sig_195 );

    SC_METHOD(thread_ap_sig_cseq_ST_st13_fsm_12);
    sensitive << ( ap_sig_206 );

    SC_METHOD(thread_ap_sig_cseq_ST_st14_fsm_13);
    sensitive << ( ap_sig_220 );

    SC_METHOD(thread_ap_sig_cseq_ST_st15_fsm_14);
    sensitive << ( ap_sig_231 );

    SC_METHOD(thread_ap_sig_cseq_ST_st16_fsm_15);
    sensitive << ( ap_sig_245 );

    SC_METHOD(thread_ap_sig_cseq_ST_st17_fsm_16);
    sensitive << ( ap_sig_256 );

    SC_METHOD(thread_ap_sig_cseq_ST_st18_fsm_17);
    sensitive << ( ap_sig_282 );

    SC_METHOD(thread_ap_sig_cseq_ST_st19_fsm_18);
    sensitive << ( ap_sig_421 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_35 );

    SC_METHOD(thread_ap_sig_cseq_ST_st20_fsm_19);
    sensitive << ( ap_sig_399 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_73 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_91 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_308 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_105 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_123 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_138 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_146 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_158 );

    SC_METHOD(thread_context_Intermediate_Hash_addr_1_reg_1297);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_context_Intermediate_Hash_addr_2_reg_1302);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_context_Intermediate_Hash_address0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( context_Intermediate_Hash_addr_1_reg_1297 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );

    SC_METHOD(thread_context_Intermediate_Hash_address1);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( context_Intermediate_Hash_addr_2_reg_1302 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );

    SC_METHOD(thread_context_Intermediate_Hash_ce0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );

    SC_METHOD(thread_context_Intermediate_Hash_ce1);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );

    SC_METHOD(thread_context_Intermediate_Hash_d0);
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( tmp_38_reg_1440 );
    sensitive << ( tmp_36_fu_1149_p2 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );

    SC_METHOD(thread_context_Intermediate_Hash_d1);
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( tmp_37_reg_1435 );
    sensitive << ( tmp_39_reg_1445 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );
    sensitive << ( tmp_35_fu_1143_p2 );

    SC_METHOD(thread_context_Intermediate_Hash_we0);
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( exitcond_fu_1080_p2 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );

    SC_METHOD(thread_context_Intermediate_Hash_we1);
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( exitcond_fu_1080_p2 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );

    SC_METHOD(thread_context_Message_Block_Index);
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );

    SC_METHOD(thread_context_Message_Block_Index_ap_vld);
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );

    SC_METHOD(thread_context_Message_Block_address0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_2_fu_615_p1 );
    sensitive << ( tmp_3_fu_636_p1 );

    SC_METHOD(thread_context_Message_Block_address1);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_7_fu_626_p1 );
    sensitive << ( tmp_8_fu_646_p1 );

    SC_METHOD(thread_context_Message_Block_ce0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_context_Message_Block_ce1);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_exitcond1_fu_971_p2);
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( t_4_reg_513 );

    SC_METHOD(thread_exitcond2_fu_874_p2);
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( t_3_reg_444 );

    SC_METHOD(thread_exitcond3_fu_765_p2);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( t_2_reg_375 );

    SC_METHOD(thread_exitcond4_fu_667_p2);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( t_1_reg_310 );

    SC_METHOD(thread_exitcond5_fu_591_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( t_reg_298 );

    SC_METHOD(thread_exitcond_fu_1080_p2);
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( t_5_reg_580 );

    SC_METHOD(thread_t_10_fu_982_p2);
    sensitive << ( t_4_reg_513 );

    SC_METHOD(thread_t_11_fu_1137_p2);
    sensitive << ( t_5_reg_580 );

    SC_METHOD(thread_t_6_fu_597_p2);
    sensitive << ( t_reg_298 );

    SC_METHOD(thread_t_7_fu_759_p2);
    sensitive << ( t_1_reg_310 );

    SC_METHOD(thread_t_8_fu_771_p2);
    sensitive << ( t_2_reg_375 );

    SC_METHOD(thread_t_9_fu_885_p2);
    sensitive << ( t_3_reg_444 );

    SC_METHOD(thread_temp_1_fu_943_p2);
    sensitive << ( tmp10_fu_937_p2 );
    sensitive << ( tmp9_fu_925_p2 );

    SC_METHOD(thread_temp_2_fu_1052_p2);
    sensitive << ( tmp13_fu_1046_p2 );
    sensitive << ( tmp12_fu_1034_p2 );

    SC_METHOD(thread_temp_3_fu_1198_p2);
    sensitive << ( tmp17_reg_1420 );
    sensitive << ( tmp16_fu_1192_p2 );

    SC_METHOD(thread_temp_fu_846_p2);
    sensitive << ( tmp6_fu_840_p2 );
    sensitive << ( tmp5_fu_828_p2 );

    SC_METHOD(thread_tmp10_fu_937_p2);
    sensitive << ( tmp11_fu_931_p2 );
    sensitive << ( tmp_28_fu_919_p2 );

    SC_METHOD(thread_tmp11_fu_931_p2);
    sensitive << ( E_s_reg_386 );

    SC_METHOD(thread_tmp12_fu_1034_p2);
    sensitive << ( W_q0 );
    sensitive << ( tmp_72_i3_fu_1002_p3 );

    SC_METHOD(thread_tmp13_fu_1046_p2);
    sensitive << ( tmp14_fu_1040_p2 );

    SC_METHOD(thread_tmp14_fu_1040_p2);
    sensitive << ( E_2_reg_455 );
    sensitive << ( tmp_33_fu_1028_p2 );

    SC_METHOD(thread_tmp15_fu_1086_p2);
    sensitive << ( E_6_reg_534 );
    sensitive << ( B_read_assign_3_reg_558 );

    SC_METHOD(thread_tmp16_fu_1192_p2);
    sensitive << ( W_q1 );
    sensitive << ( tmp_72_i4_fu_1184_p3 );

    SC_METHOD(thread_tmp17_fu_1109_p2);
    sensitive << ( tmp18_fu_1103_p2 );
    sensitive << ( tmp_40_fu_1092_p2 );

    SC_METHOD(thread_tmp18_fu_1103_p2);
    sensitive << ( E_3_reg_524 );

    SC_METHOD(thread_tmp3_fu_717_p2);
    sensitive << ( W_load_reg_1266 );
    sensitive << ( W_q1 );

    SC_METHOD(thread_tmp4_fu_722_p2);
    sensitive << ( W_q0 );
    sensitive << ( W_load_1_reg_1271 );

    SC_METHOD(thread_tmp5_fu_828_p2);
    sensitive << ( W_q0 );
    sensitive << ( tmp_72_i1_fu_796_p3 );

    SC_METHOD(thread_tmp6_fu_840_p2);
    sensitive << ( E1_reg_322 );
    sensitive << ( tmp7_fu_834_p2 );

    SC_METHOD(thread_tmp7_fu_834_p2);
    sensitive << ( tmp_24_fu_822_p2 );

    SC_METHOD(thread_tmp8_fu_913_p2);
    sensitive << ( E_4_reg_397 );
    sensitive << ( B_read_assign_1_reg_421 );

    SC_METHOD(thread_tmp9_fu_925_p2);
    sensitive << ( W_q1 );
    sensitive << ( tmp_72_i2_fu_905_p3 );

    SC_METHOD(thread_tmp_10_fu_673_p2);
    sensitive << ( t_1_reg_310 );

    SC_METHOD(thread_tmp_11_fu_679_p1);
    sensitive << ( tmp_10_fu_673_p2 );

    SC_METHOD(thread_tmp_12_fu_684_p2);
    sensitive << ( t_1_reg_310 );

    SC_METHOD(thread_tmp_13_fu_690_p1);
    sensitive << ( tmp_12_fu_684_p2 );

    SC_METHOD(thread_tmp_14_fu_695_p2);
    sensitive << ( t_1_reg_310 );

    SC_METHOD(thread_tmp_15_fu_701_p1);
    sensitive << ( tmp_14_fu_695_p2 );

    SC_METHOD(thread_tmp_16_fu_706_p2);
    sensitive << ( t_1_reg_310 );

    SC_METHOD(thread_tmp_17_fu_712_p1);
    sensitive << ( tmp_16_fu_706_p2 );

    SC_METHOD(thread_tmp_18_fu_733_p1);
    sensitive << ( word_assign_fu_727_p2 );

    SC_METHOD(thread_tmp_19_fu_754_p1);
    sensitive << ( t_1_reg_310 );

    SC_METHOD(thread_tmp_1_fu_607_p3);
    sensitive << ( tmp_fu_603_p1 );

    SC_METHOD(thread_tmp_20_fu_737_p3);
    sensitive << ( word_assign_fu_727_p2 );

    SC_METHOD(thread_tmp_21_fu_804_p2);
    sensitive << ( D_1_reg_343 );
    sensitive << ( B_read_assign_reg_354 );

    SC_METHOD(thread_tmp_22_fu_810_p2);
    sensitive << ( B_read_assign_reg_354 );

    SC_METHOD(thread_tmp_23_fu_816_p2);
    sensitive << ( E_1_reg_332 );
    sensitive << ( tmp_22_fu_810_p2 );

    SC_METHOD(thread_tmp_24_fu_822_p2);
    sensitive << ( tmp_23_fu_816_p2 );
    sensitive << ( tmp_21_fu_804_p2 );

    SC_METHOD(thread_tmp_25_fu_777_p1);
    sensitive << ( t_2_reg_375 );

    SC_METHOD(thread_tmp_26_fu_782_p1);
    sensitive << ( B_1_reg_364 );

    SC_METHOD(thread_tmp_27_fu_852_p1);
    sensitive << ( B_read_assign_reg_354 );

    SC_METHOD(thread_tmp_28_fu_919_p2);
    sensitive << ( D_2_reg_409 );
    sensitive << ( tmp8_fu_913_p2 );

    SC_METHOD(thread_tmp_29_fu_880_p1);
    sensitive << ( t_3_reg_444 );

    SC_METHOD(thread_tmp_2_fu_615_p1);
    sensitive << ( tmp_1_fu_607_p3 );

    SC_METHOD(thread_tmp_30_fu_1010_p2);
    sensitive << ( E_5_reg_466 );
    sensitive << ( D_3_reg_478 );

    SC_METHOD(thread_tmp_31_fu_1016_p2);
    sensitive << ( B_read_assign_2_reg_490 );
    sensitive << ( tmp_30_fu_1010_p2 );

    SC_METHOD(thread_tmp_32_fu_1022_p2);
    sensitive << ( E_5_reg_466 );
    sensitive << ( D_3_reg_478 );

    SC_METHOD(thread_tmp_33_fu_1028_p2);
    sensitive << ( tmp_31_fu_1016_p2 );
    sensitive << ( tmp_32_fu_1022_p2 );

    SC_METHOD(thread_tmp_34_fu_977_p1);
    sensitive << ( t_4_reg_513 );

    SC_METHOD(thread_tmp_35_fu_1143_p2);
    sensitive << ( A_reg_1291 );
    sensitive << ( B_4_reg_568 );

    SC_METHOD(thread_tmp_36_fu_1149_p2);
    sensitive << ( B_reg_1307 );
    sensitive << ( B_read_assign_3_reg_558 );

    SC_METHOD(thread_tmp_37_fu_1155_p2);
    sensitive << ( C_reg_1313 );
    sensitive << ( D_4_reg_546 );

    SC_METHOD(thread_tmp_38_fu_1160_p2);
    sensitive << ( D_reg_1331 );
    sensitive << ( E_6_reg_534 );

    SC_METHOD(thread_tmp_39_fu_1165_p2);
    sensitive << ( E_reg_1337 );
    sensitive << ( E_3_reg_524 );

    SC_METHOD(thread_tmp_3_fu_636_p1);
    sensitive << ( tmp_s_fu_631_p2 );

    SC_METHOD(thread_tmp_40_fu_1092_p2);
    sensitive << ( D_4_reg_546 );
    sensitive << ( tmp15_fu_1086_p2 );

    SC_METHOD(thread_tmp_41_fu_1098_p1);
    sensitive << ( t_5_reg_580 );

    SC_METHOD(thread_tmp_42_fu_891_p1);
    sensitive << ( B_2_reg_432 );

    SC_METHOD(thread_tmp_43_fu_949_p1);
    sensitive << ( B_read_assign_1_reg_421 );

    SC_METHOD(thread_tmp_44_fu_988_p1);
    sensitive << ( B_3_reg_501 );

    SC_METHOD(thread_tmp_45_fu_1058_p1);
    sensitive << ( B_read_assign_2_reg_490 );

    SC_METHOD(thread_tmp_46_fu_1170_p1);
    sensitive << ( B_4_reg_568 );

    SC_METHOD(thread_tmp_47_fu_1115_p1);
    sensitive << ( B_read_assign_3_reg_558 );

    SC_METHOD(thread_tmp_4_fu_641_p2);
    sensitive << ( tmp_1_reg_1211 );

    SC_METHOD(thread_tmp_5_fu_651_p1);
    sensitive << ( t_reg_298 );

    SC_METHOD(thread_tmp_6_fu_620_p2);
    sensitive << ( tmp_1_fu_607_p3 );

    SC_METHOD(thread_tmp_71_i1_fu_786_p4);
    sensitive << ( B_1_reg_364 );

    SC_METHOD(thread_tmp_71_i2_fu_895_p4);
    sensitive << ( B_2_reg_432 );

    SC_METHOD(thread_tmp_71_i3_fu_992_p4);
    sensitive << ( B_3_reg_501 );

    SC_METHOD(thread_tmp_71_i4_fu_1174_p4);
    sensitive << ( B_4_reg_568 );

    SC_METHOD(thread_tmp_71_i_i1_fu_953_p4);
    sensitive << ( B_read_assign_1_reg_421 );

    SC_METHOD(thread_tmp_71_i_i2_fu_1062_p4);
    sensitive << ( B_read_assign_2_reg_490 );

    SC_METHOD(thread_tmp_71_i_i3_fu_1119_p4);
    sensitive << ( B_read_assign_3_reg_558 );

    SC_METHOD(thread_tmp_71_i_i_fu_856_p4);
    sensitive << ( B_read_assign_reg_354 );

    SC_METHOD(thread_tmp_72_i1_fu_796_p3);
    sensitive << ( tmp_26_fu_782_p1 );
    sensitive << ( tmp_71_i1_fu_786_p4 );

    SC_METHOD(thread_tmp_72_i2_fu_905_p3);
    sensitive << ( tmp_42_fu_891_p1 );
    sensitive << ( tmp_71_i2_fu_895_p4 );

    SC_METHOD(thread_tmp_72_i3_fu_1002_p3);
    sensitive << ( tmp_44_fu_988_p1 );
    sensitive << ( tmp_71_i3_fu_992_p4 );

    SC_METHOD(thread_tmp_72_i4_fu_1184_p3);
    sensitive << ( tmp_46_fu_1170_p1 );
    sensitive << ( tmp_71_i4_fu_1174_p4 );

    SC_METHOD(thread_tmp_7_fu_626_p1);
    sensitive << ( tmp_6_fu_620_p2 );

    SC_METHOD(thread_tmp_8_fu_646_p1);
    sensitive << ( tmp_4_fu_641_p2 );

    SC_METHOD(thread_tmp_fu_603_p1);
    sensitive << ( t_reg_298 );

    SC_METHOD(thread_tmp_s_fu_631_p2);
    sensitive << ( tmp_1_reg_1211 );

    SC_METHOD(thread_word_assign_fu_727_p2);
    sensitive << ( tmp4_fu_722_p2 );
    sensitive << ( tmp3_fu_717_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond5_fu_591_p2 );
    sensitive << ( exitcond4_fu_667_p2 );
    sensitive << ( exitcond3_fu_765_p2 );
    sensitive << ( exitcond2_fu_874_p2 );
    sensitive << ( exitcond1_fu_971_p2 );
    sensitive << ( exitcond_fu_1080_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "00000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "SHA1ProcessMessageBlock_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, context_Intermediate_Hash_address0, "(port)context_Intermediate_Hash_address0");
    sc_trace(mVcdFile, context_Intermediate_Hash_ce0, "(port)context_Intermediate_Hash_ce0");
    sc_trace(mVcdFile, context_Intermediate_Hash_we0, "(port)context_Intermediate_Hash_we0");
    sc_trace(mVcdFile, context_Intermediate_Hash_d0, "(port)context_Intermediate_Hash_d0");
    sc_trace(mVcdFile, context_Intermediate_Hash_q0, "(port)context_Intermediate_Hash_q0");
    sc_trace(mVcdFile, context_Intermediate_Hash_address1, "(port)context_Intermediate_Hash_address1");
    sc_trace(mVcdFile, context_Intermediate_Hash_ce1, "(port)context_Intermediate_Hash_ce1");
    sc_trace(mVcdFile, context_Intermediate_Hash_we1, "(port)context_Intermediate_Hash_we1");
    sc_trace(mVcdFile, context_Intermediate_Hash_d1, "(port)context_Intermediate_Hash_d1");
    sc_trace(mVcdFile, context_Intermediate_Hash_q1, "(port)context_Intermediate_Hash_q1");
    sc_trace(mVcdFile, context_Message_Block_Index, "(port)context_Message_Block_Index");
    sc_trace(mVcdFile, context_Message_Block_Index_ap_vld, "(port)context_Message_Block_Index_ap_vld");
    sc_trace(mVcdFile, context_Message_Block_address0, "(port)context_Message_Block_address0");
    sc_trace(mVcdFile, context_Message_Block_ce0, "(port)context_Message_Block_ce0");
    sc_trace(mVcdFile, context_Message_Block_q0, "(port)context_Message_Block_q0");
    sc_trace(mVcdFile, context_Message_Block_address1, "(port)context_Message_Block_address1");
    sc_trace(mVcdFile, context_Message_Block_ce1, "(port)context_Message_Block_ce1");
    sc_trace(mVcdFile, context_Message_Block_q1, "(port)context_Message_Block_q1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_35, "ap_sig_35");
    sc_trace(mVcdFile, t_6_fu_597_p2, "t_6_fu_597_p2");
    sc_trace(mVcdFile, t_6_reg_1206, "t_6_reg_1206");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_73, "ap_sig_73");
    sc_trace(mVcdFile, tmp_1_fu_607_p3, "tmp_1_fu_607_p3");
    sc_trace(mVcdFile, tmp_1_reg_1211, "tmp_1_reg_1211");
    sc_trace(mVcdFile, exitcond5_fu_591_p2, "exitcond5_fu_591_p2");
    sc_trace(mVcdFile, context_Message_Block_load_reg_1227, "context_Message_Block_load_reg_1227");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_91, "ap_sig_91");
    sc_trace(mVcdFile, context_Message_Block_load_1_reg_1232, "context_Message_Block_load_1_reg_1232");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_105, "ap_sig_105");
    sc_trace(mVcdFile, exitcond4_fu_667_p2, "exitcond4_fu_667_p2");
    sc_trace(mVcdFile, W_q0, "W_q0");
    sc_trace(mVcdFile, W_load_reg_1266, "W_load_reg_1266");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_123, "ap_sig_123");
    sc_trace(mVcdFile, W_q1, "W_q1");
    sc_trace(mVcdFile, W_load_1_reg_1271, "W_load_1_reg_1271");
    sc_trace(mVcdFile, t_7_fu_759_p2, "t_7_fu_759_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_138, "ap_sig_138");
    sc_trace(mVcdFile, A_reg_1291, "A_reg_1291");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_146, "ap_sig_146");
    sc_trace(mVcdFile, context_Intermediate_Hash_addr_1_reg_1297, "context_Intermediate_Hash_addr_1_reg_1297");
    sc_trace(mVcdFile, context_Intermediate_Hash_addr_2_reg_1302, "context_Intermediate_Hash_addr_2_reg_1302");
    sc_trace(mVcdFile, B_reg_1307, "B_reg_1307");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_158, "ap_sig_158");
    sc_trace(mVcdFile, C_reg_1313, "C_reg_1313");
    sc_trace(mVcdFile, D_reg_1331, "D_reg_1331");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_171, "ap_sig_171");
    sc_trace(mVcdFile, E_reg_1337, "E_reg_1337");
    sc_trace(mVcdFile, t_8_fu_771_p2, "t_8_fu_771_p2");
    sc_trace(mVcdFile, t_8_reg_1346, "t_8_reg_1346");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_181, "ap_sig_181");
    sc_trace(mVcdFile, exitcond3_fu_765_p2, "exitcond3_fu_765_p2");
    sc_trace(mVcdFile, temp_fu_846_p2, "temp_fu_846_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st12_fsm_11, "ap_sig_cseq_ST_st12_fsm_11");
    sc_trace(mVcdFile, ap_sig_195, "ap_sig_195");
    sc_trace(mVcdFile, C_1_fu_866_p3, "C_1_fu_866_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st13_fsm_12, "ap_sig_cseq_ST_st13_fsm_12");
    sc_trace(mVcdFile, ap_sig_206, "ap_sig_206");
    sc_trace(mVcdFile, exitcond2_fu_874_p2, "exitcond2_fu_874_p2");
    sc_trace(mVcdFile, t_9_fu_885_p2, "t_9_fu_885_p2");
    sc_trace(mVcdFile, t_9_reg_1374, "t_9_reg_1374");
    sc_trace(mVcdFile, temp_1_fu_943_p2, "temp_1_fu_943_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st14_fsm_13, "ap_sig_cseq_ST_st14_fsm_13");
    sc_trace(mVcdFile, ap_sig_220, "ap_sig_220");
    sc_trace(mVcdFile, C_2_fu_963_p3, "C_2_fu_963_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st15_fsm_14, "ap_sig_cseq_ST_st15_fsm_14");
    sc_trace(mVcdFile, ap_sig_231, "ap_sig_231");
    sc_trace(mVcdFile, exitcond1_fu_971_p2, "exitcond1_fu_971_p2");
    sc_trace(mVcdFile, t_10_fu_982_p2, "t_10_fu_982_p2");
    sc_trace(mVcdFile, t_10_reg_1397, "t_10_reg_1397");
    sc_trace(mVcdFile, temp_2_fu_1052_p2, "temp_2_fu_1052_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st16_fsm_15, "ap_sig_cseq_ST_st16_fsm_15");
    sc_trace(mVcdFile, ap_sig_245, "ap_sig_245");
    sc_trace(mVcdFile, C_3_fu_1072_p3, "C_3_fu_1072_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st17_fsm_16, "ap_sig_cseq_ST_st17_fsm_16");
    sc_trace(mVcdFile, ap_sig_256, "ap_sig_256");
    sc_trace(mVcdFile, exitcond_fu_1080_p2, "exitcond_fu_1080_p2");
    sc_trace(mVcdFile, tmp17_fu_1109_p2, "tmp17_fu_1109_p2");
    sc_trace(mVcdFile, tmp17_reg_1420, "tmp17_reg_1420");
    sc_trace(mVcdFile, C_4_fu_1129_p3, "C_4_fu_1129_p3");
    sc_trace(mVcdFile, C_4_reg_1425, "C_4_reg_1425");
    sc_trace(mVcdFile, t_11_fu_1137_p2, "t_11_fu_1137_p2");
    sc_trace(mVcdFile, t_11_reg_1430, "t_11_reg_1430");
    sc_trace(mVcdFile, tmp_37_fu_1155_p2, "tmp_37_fu_1155_p2");
    sc_trace(mVcdFile, tmp_37_reg_1435, "tmp_37_reg_1435");
    sc_trace(mVcdFile, tmp_38_fu_1160_p2, "tmp_38_fu_1160_p2");
    sc_trace(mVcdFile, tmp_38_reg_1440, "tmp_38_reg_1440");
    sc_trace(mVcdFile, tmp_39_fu_1165_p2, "tmp_39_fu_1165_p2");
    sc_trace(mVcdFile, tmp_39_reg_1445, "tmp_39_reg_1445");
    sc_trace(mVcdFile, temp_3_fu_1198_p2, "temp_3_fu_1198_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st18_fsm_17, "ap_sig_cseq_ST_st18_fsm_17");
    sc_trace(mVcdFile, ap_sig_282, "ap_sig_282");
    sc_trace(mVcdFile, W_address0, "W_address0");
    sc_trace(mVcdFile, W_ce0, "W_ce0");
    sc_trace(mVcdFile, W_we0, "W_we0");
    sc_trace(mVcdFile, W_d0, "W_d0");
    sc_trace(mVcdFile, W_address1, "W_address1");
    sc_trace(mVcdFile, W_ce1, "W_ce1");
    sc_trace(mVcdFile, W_we1, "W_we1");
    sc_trace(mVcdFile, W_d1, "W_d1");
    sc_trace(mVcdFile, t_reg_298, "t_reg_298");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_308, "ap_sig_308");
    sc_trace(mVcdFile, t_1_reg_310, "t_1_reg_310");
    sc_trace(mVcdFile, E1_reg_322, "E1_reg_322");
    sc_trace(mVcdFile, E_1_reg_332, "E_1_reg_332");
    sc_trace(mVcdFile, D_1_reg_343, "D_1_reg_343");
    sc_trace(mVcdFile, B_read_assign_reg_354, "B_read_assign_reg_354");
    sc_trace(mVcdFile, B_1_reg_364, "B_1_reg_364");
    sc_trace(mVcdFile, t_2_reg_375, "t_2_reg_375");
    sc_trace(mVcdFile, E_4_reg_397, "E_4_reg_397");
    sc_trace(mVcdFile, E_s_reg_386, "E_s_reg_386");
    sc_trace(mVcdFile, D_2_reg_409, "D_2_reg_409");
    sc_trace(mVcdFile, B_2_reg_432, "B_2_reg_432");
    sc_trace(mVcdFile, B_read_assign_1_reg_421, "B_read_assign_1_reg_421");
    sc_trace(mVcdFile, t_3_reg_444, "t_3_reg_444");
    sc_trace(mVcdFile, E_5_reg_466, "E_5_reg_466");
    sc_trace(mVcdFile, E_2_reg_455, "E_2_reg_455");
    sc_trace(mVcdFile, D_3_reg_478, "D_3_reg_478");
    sc_trace(mVcdFile, B_3_reg_501, "B_3_reg_501");
    sc_trace(mVcdFile, B_read_assign_2_reg_490, "B_read_assign_2_reg_490");
    sc_trace(mVcdFile, t_4_reg_513, "t_4_reg_513");
    sc_trace(mVcdFile, E_6_reg_534, "E_6_reg_534");
    sc_trace(mVcdFile, E_3_reg_524, "E_3_reg_524");
    sc_trace(mVcdFile, D_4_reg_546, "D_4_reg_546");
    sc_trace(mVcdFile, B_4_reg_568, "B_4_reg_568");
    sc_trace(mVcdFile, B_read_assign_3_reg_558, "B_read_assign_3_reg_558");
    sc_trace(mVcdFile, t_5_reg_580, "t_5_reg_580");
    sc_trace(mVcdFile, tmp_2_fu_615_p1, "tmp_2_fu_615_p1");
    sc_trace(mVcdFile, tmp_7_fu_626_p1, "tmp_7_fu_626_p1");
    sc_trace(mVcdFile, tmp_3_fu_636_p1, "tmp_3_fu_636_p1");
    sc_trace(mVcdFile, tmp_8_fu_646_p1, "tmp_8_fu_646_p1");
    sc_trace(mVcdFile, tmp_5_fu_651_p1, "tmp_5_fu_651_p1");
    sc_trace(mVcdFile, tmp_11_fu_679_p1, "tmp_11_fu_679_p1");
    sc_trace(mVcdFile, tmp_13_fu_690_p1, "tmp_13_fu_690_p1");
    sc_trace(mVcdFile, tmp_15_fu_701_p1, "tmp_15_fu_701_p1");
    sc_trace(mVcdFile, tmp_17_fu_712_p1, "tmp_17_fu_712_p1");
    sc_trace(mVcdFile, tmp_19_fu_754_p1, "tmp_19_fu_754_p1");
    sc_trace(mVcdFile, tmp_25_fu_777_p1, "tmp_25_fu_777_p1");
    sc_trace(mVcdFile, tmp_29_fu_880_p1, "tmp_29_fu_880_p1");
    sc_trace(mVcdFile, tmp_34_fu_977_p1, "tmp_34_fu_977_p1");
    sc_trace(mVcdFile, tmp_41_fu_1098_p1, "tmp_41_fu_1098_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st20_fsm_19, "ap_sig_cseq_ST_st20_fsm_19");
    sc_trace(mVcdFile, ap_sig_399, "ap_sig_399");
    sc_trace(mVcdFile, tmp_36_fu_1149_p2, "tmp_36_fu_1149_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st19_fsm_18, "ap_sig_cseq_ST_st19_fsm_18");
    sc_trace(mVcdFile, ap_sig_421, "ap_sig_421");
    sc_trace(mVcdFile, tmp_35_fu_1143_p2, "tmp_35_fu_1143_p2");
    sc_trace(mVcdFile, tmp_fu_603_p1, "tmp_fu_603_p1");
    sc_trace(mVcdFile, tmp_6_fu_620_p2, "tmp_6_fu_620_p2");
    sc_trace(mVcdFile, tmp_s_fu_631_p2, "tmp_s_fu_631_p2");
    sc_trace(mVcdFile, tmp_4_fu_641_p2, "tmp_4_fu_641_p2");
    sc_trace(mVcdFile, tmp_10_fu_673_p2, "tmp_10_fu_673_p2");
    sc_trace(mVcdFile, tmp_12_fu_684_p2, "tmp_12_fu_684_p2");
    sc_trace(mVcdFile, tmp_14_fu_695_p2, "tmp_14_fu_695_p2");
    sc_trace(mVcdFile, tmp_16_fu_706_p2, "tmp_16_fu_706_p2");
    sc_trace(mVcdFile, tmp4_fu_722_p2, "tmp4_fu_722_p2");
    sc_trace(mVcdFile, tmp3_fu_717_p2, "tmp3_fu_717_p2");
    sc_trace(mVcdFile, word_assign_fu_727_p2, "word_assign_fu_727_p2");
    sc_trace(mVcdFile, tmp_18_fu_733_p1, "tmp_18_fu_733_p1");
    sc_trace(mVcdFile, tmp_20_fu_737_p3, "tmp_20_fu_737_p3");
    sc_trace(mVcdFile, tmp_26_fu_782_p1, "tmp_26_fu_782_p1");
    sc_trace(mVcdFile, tmp_71_i1_fu_786_p4, "tmp_71_i1_fu_786_p4");
    sc_trace(mVcdFile, tmp_22_fu_810_p2, "tmp_22_fu_810_p2");
    sc_trace(mVcdFile, tmp_23_fu_816_p2, "tmp_23_fu_816_p2");
    sc_trace(mVcdFile, tmp_21_fu_804_p2, "tmp_21_fu_804_p2");
    sc_trace(mVcdFile, tmp_72_i1_fu_796_p3, "tmp_72_i1_fu_796_p3");
    sc_trace(mVcdFile, tmp_24_fu_822_p2, "tmp_24_fu_822_p2");
    sc_trace(mVcdFile, tmp7_fu_834_p2, "tmp7_fu_834_p2");
    sc_trace(mVcdFile, tmp6_fu_840_p2, "tmp6_fu_840_p2");
    sc_trace(mVcdFile, tmp5_fu_828_p2, "tmp5_fu_828_p2");
    sc_trace(mVcdFile, tmp_27_fu_852_p1, "tmp_27_fu_852_p1");
    sc_trace(mVcdFile, tmp_71_i_i_fu_856_p4, "tmp_71_i_i_fu_856_p4");
    sc_trace(mVcdFile, tmp_42_fu_891_p1, "tmp_42_fu_891_p1");
    sc_trace(mVcdFile, tmp_71_i2_fu_895_p4, "tmp_71_i2_fu_895_p4");
    sc_trace(mVcdFile, tmp8_fu_913_p2, "tmp8_fu_913_p2");
    sc_trace(mVcdFile, tmp_72_i2_fu_905_p3, "tmp_72_i2_fu_905_p3");
    sc_trace(mVcdFile, tmp11_fu_931_p2, "tmp11_fu_931_p2");
    sc_trace(mVcdFile, tmp_28_fu_919_p2, "tmp_28_fu_919_p2");
    sc_trace(mVcdFile, tmp10_fu_937_p2, "tmp10_fu_937_p2");
    sc_trace(mVcdFile, tmp9_fu_925_p2, "tmp9_fu_925_p2");
    sc_trace(mVcdFile, tmp_43_fu_949_p1, "tmp_43_fu_949_p1");
    sc_trace(mVcdFile, tmp_71_i_i1_fu_953_p4, "tmp_71_i_i1_fu_953_p4");
    sc_trace(mVcdFile, tmp_44_fu_988_p1, "tmp_44_fu_988_p1");
    sc_trace(mVcdFile, tmp_71_i3_fu_992_p4, "tmp_71_i3_fu_992_p4");
    sc_trace(mVcdFile, tmp_30_fu_1010_p2, "tmp_30_fu_1010_p2");
    sc_trace(mVcdFile, tmp_31_fu_1016_p2, "tmp_31_fu_1016_p2");
    sc_trace(mVcdFile, tmp_32_fu_1022_p2, "tmp_32_fu_1022_p2");
    sc_trace(mVcdFile, tmp_72_i3_fu_1002_p3, "tmp_72_i3_fu_1002_p3");
    sc_trace(mVcdFile, tmp_33_fu_1028_p2, "tmp_33_fu_1028_p2");
    sc_trace(mVcdFile, tmp14_fu_1040_p2, "tmp14_fu_1040_p2");
    sc_trace(mVcdFile, tmp13_fu_1046_p2, "tmp13_fu_1046_p2");
    sc_trace(mVcdFile, tmp12_fu_1034_p2, "tmp12_fu_1034_p2");
    sc_trace(mVcdFile, tmp_45_fu_1058_p1, "tmp_45_fu_1058_p1");
    sc_trace(mVcdFile, tmp_71_i_i2_fu_1062_p4, "tmp_71_i_i2_fu_1062_p4");
    sc_trace(mVcdFile, tmp15_fu_1086_p2, "tmp15_fu_1086_p2");
    sc_trace(mVcdFile, tmp18_fu_1103_p2, "tmp18_fu_1103_p2");
    sc_trace(mVcdFile, tmp_40_fu_1092_p2, "tmp_40_fu_1092_p2");
    sc_trace(mVcdFile, tmp_47_fu_1115_p1, "tmp_47_fu_1115_p1");
    sc_trace(mVcdFile, tmp_71_i_i3_fu_1119_p4, "tmp_71_i_i3_fu_1119_p4");
    sc_trace(mVcdFile, tmp_46_fu_1170_p1, "tmp_46_fu_1170_p1");
    sc_trace(mVcdFile, tmp_71_i4_fu_1174_p4, "tmp_71_i4_fu_1174_p4");
    sc_trace(mVcdFile, tmp_72_i4_fu_1184_p3, "tmp_72_i4_fu_1184_p3");
    sc_trace(mVcdFile, tmp16_fu_1192_p2, "tmp16_fu_1192_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("SHA1ProcessMessageBlock.hdltvin.dat");
    mHdltvoutHandle.open("SHA1ProcessMessageBlock.hdltvout.dat");
}

SHA1ProcessMessageBlock::~SHA1ProcessMessageBlock() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete W_U;
}

void SHA1ProcessMessageBlock::thread_ap_clk_no_reset_() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        B_1_reg_364 = temp_fu_846_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        B_1_reg_364 = A_reg_1291.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_765_p2.read()))) {
        B_2_reg_432 = B_1_reg_364.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        B_2_reg_432 = temp_1_fu_943_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_874_p2.read()))) {
        B_3_reg_501 = B_2_reg_432.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        B_3_reg_501 = temp_2_fu_1052_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_971_p2.read()))) {
        B_4_reg_568 = B_3_reg_501.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        B_4_reg_568 = temp_3_fu_1198_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_765_p2.read()))) {
        B_read_assign_1_reg_421 = B_read_assign_reg_354.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        B_read_assign_1_reg_421 = B_2_reg_432.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_874_p2.read()))) {
        B_read_assign_2_reg_490 = B_read_assign_1_reg_421.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        B_read_assign_2_reg_490 = B_3_reg_501.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_971_p2.read()))) {
        B_read_assign_3_reg_558 = B_read_assign_2_reg_490.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        B_read_assign_3_reg_558 = B_4_reg_568.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        B_read_assign_reg_354 = B_1_reg_364.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        B_read_assign_reg_354 = B_reg_1307.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        D_1_reg_343 = C_1_fu_866_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        D_1_reg_343 = C_reg_1313.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_765_p2.read()))) {
        D_2_reg_409 = D_1_reg_343.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        D_2_reg_409 = C_2_fu_963_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_874_p2.read()))) {
        D_3_reg_478 = D_2_reg_409.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        D_3_reg_478 = C_3_fu_1072_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_971_p2.read()))) {
        D_4_reg_546 = D_3_reg_478.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        D_4_reg_546 = C_4_reg_1425.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        E1_reg_322 = E_1_reg_332.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        E1_reg_322 = context_Intermediate_Hash_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        E_1_reg_332 = D_1_reg_343.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        E_1_reg_332 = context_Intermediate_Hash_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_874_p2.read()))) {
        E_2_reg_455 = E_s_reg_386.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        E_2_reg_455 = E_5_reg_466.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_971_p2.read()))) {
        E_3_reg_524 = E_2_reg_455.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        E_3_reg_524 = E_6_reg_534.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_765_p2.read()))) {
        E_4_reg_397 = E_1_reg_332.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        E_4_reg_397 = D_2_reg_409.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_874_p2.read()))) {
        E_5_reg_466 = E_4_reg_397.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        E_5_reg_466 = D_3_reg_478.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_971_p2.read()))) {
        E_6_reg_534 = E_5_reg_466.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        E_6_reg_534 = D_4_reg_546.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_765_p2.read()))) {
        E_s_reg_386 = E1_reg_322.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        E_s_reg_386 = E_4_reg_397.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(exitcond5_fu_591_p2.read(), ap_const_lv1_0))) {
        t_1_reg_310 = ap_const_lv7_10;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        t_1_reg_310 = t_7_fu_759_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        t_2_reg_375 = t_8_reg_1346.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        t_2_reg_375 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_765_p2.read()))) {
        t_3_reg_444 = ap_const_lv6_14;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        t_3_reg_444 = t_9_reg_1374.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_874_p2.read()))) {
        t_4_reg_513 = ap_const_lv6_28;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        t_4_reg_513 = t_10_reg_1397.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_971_p2.read()))) {
        t_5_reg_580 = ap_const_lv7_3C;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        t_5_reg_580 = t_11_reg_1430.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        t_reg_298 = t_6_reg_1206.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        t_reg_298 = ap_const_lv5_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        A_reg_1291 = context_Intermediate_Hash_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        B_reg_1307 = context_Intermediate_Hash_q0.read();
        C_reg_1313 = context_Intermediate_Hash_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_1080_p2.read()))) {
        C_4_reg_1425 = C_4_fu_1129_p3.read();
        t_11_reg_1430 = t_11_fu_1137_p2.read();
        tmp17_reg_1420 = tmp17_fu_1109_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        D_reg_1331 = context_Intermediate_Hash_q1.read();
        E_reg_1337 = context_Intermediate_Hash_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        W_load_1_reg_1271 = W_q1.read();
        W_load_reg_1266 = W_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        context_Message_Block_load_1_reg_1232 = context_Message_Block_q1.read();
        context_Message_Block_load_reg_1227 = context_Message_Block_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_971_p2.read()))) {
        t_10_reg_1397 = t_10_fu_982_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        t_6_reg_1206 = t_6_fu_597_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        t_8_reg_1346 = t_8_fu_771_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_874_p2.read()))) {
        t_9_reg_1374 = t_9_fu_885_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && esl_seteq<1,1,1>(exitcond5_fu_591_p2.read(), ap_const_lv1_0))) {
        tmp_1_reg_1211 = tmp_1_fu_607_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_1080_p2.read()))) {
        tmp_37_reg_1435 = tmp_37_fu_1155_p2.read();
        tmp_38_reg_1440 = tmp_38_fu_1160_p2.read();
        tmp_39_reg_1445 = tmp_39_fu_1165_p2.read();
    }
}

void SHA1ProcessMessageBlock::thread_C_1_fu_866_p3() {
    C_1_fu_866_p3 = esl_concat<2,30>(tmp_27_fu_852_p1.read(), tmp_71_i_i_fu_856_p4.read());
}

void SHA1ProcessMessageBlock::thread_C_2_fu_963_p3() {
    C_2_fu_963_p3 = esl_concat<2,30>(tmp_43_fu_949_p1.read(), tmp_71_i_i1_fu_953_p4.read());
}

void SHA1ProcessMessageBlock::thread_C_3_fu_1072_p3() {
    C_3_fu_1072_p3 = esl_concat<2,30>(tmp_45_fu_1058_p1.read(), tmp_71_i_i2_fu_1062_p4.read());
}

void SHA1ProcessMessageBlock::thread_C_4_fu_1129_p3() {
    C_4_fu_1129_p3 = esl_concat<2,30>(tmp_47_fu_1115_p1.read(), tmp_71_i_i3_fu_1119_p4.read());
}

void SHA1ProcessMessageBlock::thread_W_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        W_address0 =  (sc_lv<7>) (tmp_5_fu_651_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        W_address0 =  (sc_lv<7>) (tmp_34_fu_977_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        W_address0 =  (sc_lv<7>) (tmp_25_fu_777_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        W_address0 =  (sc_lv<7>) (tmp_17_fu_712_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        W_address0 =  (sc_lv<7>) (tmp_11_fu_679_p1.read());
    } else {
        W_address0 = "XXXXXXX";
    }
}

void SHA1ProcessMessageBlock::thread_W_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        W_address1 =  (sc_lv<7>) (tmp_19_fu_754_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read())) {
        W_address1 =  (sc_lv<7>) (tmp_41_fu_1098_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        W_address1 =  (sc_lv<7>) (tmp_29_fu_880_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        W_address1 =  (sc_lv<7>) (tmp_15_fu_701_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        W_address1 =  (sc_lv<7>) (tmp_13_fu_690_p1.read());
    } else {
        W_address1 = "XXXXXXX";
    }
}

void SHA1ProcessMessageBlock::thread_W_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()))) {
        W_ce0 = ap_const_logic_1;
    } else {
        W_ce0 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_W_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()))) {
        W_ce1 = ap_const_logic_1;
    } else {
        W_ce1 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_W_d0() {
    W_d0 = esl_concat<24,8>(esl_concat<16,8>(esl_concat<8,8>(context_Message_Block_load_reg_1227.read(), context_Message_Block_load_1_reg_1232.read()), context_Message_Block_q0.read()), context_Message_Block_q1.read());
}

void SHA1ProcessMessageBlock::thread_W_d1() {
    W_d1 = esl_concat<31,1>(tmp_18_fu_733_p1.read(), tmp_20_fu_737_p3.read());
}

void SHA1ProcessMessageBlock::thread_W_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()))) {
        W_we0 = ap_const_logic_1;
    } else {
        W_we0 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_W_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()))) {
        W_we1 = ap_const_logic_1;
    } else {
        W_we1 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_105() {
    ap_sig_105 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void SHA1ProcessMessageBlock::thread_ap_sig_123() {
    ap_sig_123 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void SHA1ProcessMessageBlock::thread_ap_sig_138() {
    ap_sig_138 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void SHA1ProcessMessageBlock::thread_ap_sig_146() {
    ap_sig_146 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void SHA1ProcessMessageBlock::thread_ap_sig_158() {
    ap_sig_158 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void SHA1ProcessMessageBlock::thread_ap_sig_171() {
    ap_sig_171 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void SHA1ProcessMessageBlock::thread_ap_sig_181() {
    ap_sig_181 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void SHA1ProcessMessageBlock::thread_ap_sig_195() {
    ap_sig_195 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(11, 11));
}

void SHA1ProcessMessageBlock::thread_ap_sig_206() {
    ap_sig_206 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(12, 12));
}

void SHA1ProcessMessageBlock::thread_ap_sig_220() {
    ap_sig_220 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(13, 13));
}

void SHA1ProcessMessageBlock::thread_ap_sig_231() {
    ap_sig_231 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(14, 14));
}

void SHA1ProcessMessageBlock::thread_ap_sig_245() {
    ap_sig_245 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(15, 15));
}

void SHA1ProcessMessageBlock::thread_ap_sig_256() {
    ap_sig_256 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(16, 16));
}

void SHA1ProcessMessageBlock::thread_ap_sig_282() {
    ap_sig_282 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(17, 17));
}

void SHA1ProcessMessageBlock::thread_ap_sig_308() {
    ap_sig_308 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void SHA1ProcessMessageBlock::thread_ap_sig_35() {
    ap_sig_35 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void SHA1ProcessMessageBlock::thread_ap_sig_399() {
    ap_sig_399 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(19, 19));
}

void SHA1ProcessMessageBlock::thread_ap_sig_421() {
    ap_sig_421 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(18, 18));
}

void SHA1ProcessMessageBlock::thread_ap_sig_73() {
    ap_sig_73 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void SHA1ProcessMessageBlock::thread_ap_sig_91() {
    ap_sig_91 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_171.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_181.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st12_fsm_11() {
    if (ap_sig_195.read()) {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st13_fsm_12() {
    if (ap_sig_206.read()) {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st14_fsm_13() {
    if (ap_sig_220.read()) {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st15_fsm_14() {
    if (ap_sig_231.read()) {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st16_fsm_15() {
    if (ap_sig_245.read()) {
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st17_fsm_16() {
    if (ap_sig_256.read()) {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st18_fsm_17() {
    if (ap_sig_282.read()) {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st19_fsm_18() {
    if (ap_sig_421.read()) {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_35.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st20_fsm_19() {
    if (ap_sig_399.read()) {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_73.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_91.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_308.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_105.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_123.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_138.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_146.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_158.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_context_Intermediate_Hash_addr_1_reg_1297() {
    context_Intermediate_Hash_addr_1_reg_1297 =  (sc_lv<3>) (ap_const_lv64_1);
}

void SHA1ProcessMessageBlock::thread_context_Intermediate_Hash_addr_2_reg_1302() {
    context_Intermediate_Hash_addr_2_reg_1302 =  (sc_lv<3>) (ap_const_lv64_2);
}

void SHA1ProcessMessageBlock::thread_context_Intermediate_Hash_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        context_Intermediate_Hash_address0 =  (sc_lv<3>) (ap_const_lv64_3);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read())) {
        context_Intermediate_Hash_address0 = context_Intermediate_Hash_addr_1_reg_1297.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        context_Intermediate_Hash_address0 =  (sc_lv<3>) (ap_const_lv64_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        context_Intermediate_Hash_address0 =  (sc_lv<3>) (ap_const_lv64_1);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        context_Intermediate_Hash_address0 =  (sc_lv<3>) (ap_const_lv64_0);
    } else {
        context_Intermediate_Hash_address0 =  (sc_lv<3>) ("XXX");
    }
}

void SHA1ProcessMessageBlock::thread_context_Intermediate_Hash_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        context_Intermediate_Hash_address1 =  (sc_lv<3>) (ap_const_lv64_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        context_Intermediate_Hash_address1 = context_Intermediate_Hash_addr_2_reg_1302.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read())) {
        context_Intermediate_Hash_address1 =  (sc_lv<3>) (ap_const_lv64_0);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        context_Intermediate_Hash_address1 =  (sc_lv<3>) (ap_const_lv64_3);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        context_Intermediate_Hash_address1 =  (sc_lv<3>) (ap_const_lv64_2);
    } else {
        context_Intermediate_Hash_address1 =  (sc_lv<3>) ("XXX");
    }
}

void SHA1ProcessMessageBlock::thread_context_Intermediate_Hash_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read()))) {
        context_Intermediate_Hash_ce0 = ap_const_logic_1;
    } else {
        context_Intermediate_Hash_ce0 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_context_Intermediate_Hash_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read()))) {
        context_Intermediate_Hash_ce1 = ap_const_logic_1;
    } else {
        context_Intermediate_Hash_ce1 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_context_Intermediate_Hash_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        context_Intermediate_Hash_d0 = tmp_38_reg_1440.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read())) {
        context_Intermediate_Hash_d0 = tmp_36_fu_1149_p2.read();
    } else {
        context_Intermediate_Hash_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void SHA1ProcessMessageBlock::thread_context_Intermediate_Hash_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        context_Intermediate_Hash_d1 = tmp_39_reg_1445.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        context_Intermediate_Hash_d1 = tmp_37_reg_1435.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read())) {
        context_Intermediate_Hash_d1 = tmp_35_fu_1143_p2.read();
    } else {
        context_Intermediate_Hash_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void SHA1ProcessMessageBlock::thread_context_Intermediate_Hash_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_1080_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read()))) {
        context_Intermediate_Hash_we0 = ap_const_logic_1;
    } else {
        context_Intermediate_Hash_we0 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_context_Intermediate_Hash_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_1080_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read()))) {
        context_Intermediate_Hash_we1 = ap_const_logic_1;
    } else {
        context_Intermediate_Hash_we1 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_context_Message_Block_Index() {
    context_Message_Block_Index = ap_const_lv16_0;
}

void SHA1ProcessMessageBlock::thread_context_Message_Block_Index_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        context_Message_Block_Index_ap_vld = ap_const_logic_1;
    } else {
        context_Message_Block_Index_ap_vld = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_context_Message_Block_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        context_Message_Block_address0 =  (sc_lv<6>) (tmp_3_fu_636_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        context_Message_Block_address0 =  (sc_lv<6>) (tmp_2_fu_615_p1.read());
    } else {
        context_Message_Block_address0 =  (sc_lv<6>) ("XXXXXX");
    }
}

void SHA1ProcessMessageBlock::thread_context_Message_Block_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        context_Message_Block_address1 =  (sc_lv<6>) (tmp_8_fu_646_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        context_Message_Block_address1 =  (sc_lv<6>) (tmp_7_fu_626_p1.read());
    } else {
        context_Message_Block_address1 =  (sc_lv<6>) ("XXXXXX");
    }
}

void SHA1ProcessMessageBlock::thread_context_Message_Block_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()))) {
        context_Message_Block_ce0 = ap_const_logic_1;
    } else {
        context_Message_Block_ce0 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_context_Message_Block_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()))) {
        context_Message_Block_ce1 = ap_const_logic_1;
    } else {
        context_Message_Block_ce1 = ap_const_logic_0;
    }
}

void SHA1ProcessMessageBlock::thread_exitcond1_fu_971_p2() {
    exitcond1_fu_971_p2 = (!t_4_reg_513.read().is_01() || !ap_const_lv6_3C.is_01())? sc_lv<1>(): sc_lv<1>(t_4_reg_513.read() == ap_const_lv6_3C);
}

void SHA1ProcessMessageBlock::thread_exitcond2_fu_874_p2() {
    exitcond2_fu_874_p2 = (!t_3_reg_444.read().is_01() || !ap_const_lv6_28.is_01())? sc_lv<1>(): sc_lv<1>(t_3_reg_444.read() == ap_const_lv6_28);
}

void SHA1ProcessMessageBlock::thread_exitcond3_fu_765_p2() {
    exitcond3_fu_765_p2 = (!t_2_reg_375.read().is_01() || !ap_const_lv5_14.is_01())? sc_lv<1>(): sc_lv<1>(t_2_reg_375.read() == ap_const_lv5_14);
}

void SHA1ProcessMessageBlock::thread_exitcond4_fu_667_p2() {
    exitcond4_fu_667_p2 = (!t_1_reg_310.read().is_01() || !ap_const_lv7_50.is_01())? sc_lv<1>(): sc_lv<1>(t_1_reg_310.read() == ap_const_lv7_50);
}

void SHA1ProcessMessageBlock::thread_exitcond5_fu_591_p2() {
    exitcond5_fu_591_p2 = (!t_reg_298.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(t_reg_298.read() == ap_const_lv5_10);
}

void SHA1ProcessMessageBlock::thread_exitcond_fu_1080_p2() {
    exitcond_fu_1080_p2 = (!t_5_reg_580.read().is_01() || !ap_const_lv7_50.is_01())? sc_lv<1>(): sc_lv<1>(t_5_reg_580.read() == ap_const_lv7_50);
}

void SHA1ProcessMessageBlock::thread_t_10_fu_982_p2() {
    t_10_fu_982_p2 = (!ap_const_lv6_1.is_01() || !t_4_reg_513.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_1) + sc_biguint<6>(t_4_reg_513.read()));
}

void SHA1ProcessMessageBlock::thread_t_11_fu_1137_p2() {
    t_11_fu_1137_p2 = (!ap_const_lv7_1.is_01() || !t_5_reg_580.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_1) + sc_biguint<7>(t_5_reg_580.read()));
}

void SHA1ProcessMessageBlock::thread_t_6_fu_597_p2() {
    t_6_fu_597_p2 = (!t_reg_298.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(t_reg_298.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void SHA1ProcessMessageBlock::thread_t_7_fu_759_p2() {
    t_7_fu_759_p2 = (!ap_const_lv7_1.is_01() || !t_1_reg_310.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_1) + sc_biguint<7>(t_1_reg_310.read()));
}

void SHA1ProcessMessageBlock::thread_t_8_fu_771_p2() {
    t_8_fu_771_p2 = (!t_2_reg_375.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(t_2_reg_375.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void SHA1ProcessMessageBlock::thread_t_9_fu_885_p2() {
    t_9_fu_885_p2 = (!ap_const_lv6_1.is_01() || !t_3_reg_444.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_1) + sc_biguint<6>(t_3_reg_444.read()));
}

void SHA1ProcessMessageBlock::thread_temp_1_fu_943_p2() {
    temp_1_fu_943_p2 = (!tmp10_fu_937_p2.read().is_01() || !tmp9_fu_925_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp10_fu_937_p2.read()) + sc_biguint<32>(tmp9_fu_925_p2.read()));
}

void SHA1ProcessMessageBlock::thread_temp_2_fu_1052_p2() {
    temp_2_fu_1052_p2 = (!tmp13_fu_1046_p2.read().is_01() || !tmp12_fu_1034_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp13_fu_1046_p2.read()) + sc_biguint<32>(tmp12_fu_1034_p2.read()));
}

void SHA1ProcessMessageBlock::thread_temp_3_fu_1198_p2() {
    temp_3_fu_1198_p2 = (!tmp17_reg_1420.read().is_01() || !tmp16_fu_1192_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp17_reg_1420.read()) + sc_biguint<32>(tmp16_fu_1192_p2.read()));
}

void SHA1ProcessMessageBlock::thread_temp_fu_846_p2() {
    temp_fu_846_p2 = (!tmp6_fu_840_p2.read().is_01() || !tmp5_fu_828_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp6_fu_840_p2.read()) + sc_biguint<32>(tmp5_fu_828_p2.read()));
}

void SHA1ProcessMessageBlock::thread_tmp10_fu_937_p2() {
    tmp10_fu_937_p2 = (!tmp11_fu_931_p2.read().is_01() || !tmp_28_fu_919_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp11_fu_931_p2.read()) + sc_biguint<32>(tmp_28_fu_919_p2.read()));
}

void SHA1ProcessMessageBlock::thread_tmp11_fu_931_p2() {
    tmp11_fu_931_p2 = (!ap_const_lv32_6ED9EBA1.is_01() || !E_s_reg_386.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_6ED9EBA1) + sc_biguint<32>(E_s_reg_386.read()));
}

void SHA1ProcessMessageBlock::thread_tmp12_fu_1034_p2() {
    tmp12_fu_1034_p2 = (!W_q0.read().is_01() || !tmp_72_i3_fu_1002_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(W_q0.read()) + sc_biguint<32>(tmp_72_i3_fu_1002_p3.read()));
}

void SHA1ProcessMessageBlock::thread_tmp13_fu_1046_p2() {
    tmp13_fu_1046_p2 = (!ap_const_lv32_8F1BBCDC.is_01() || !tmp14_fu_1040_p2.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_8F1BBCDC) + sc_biguint<32>(tmp14_fu_1040_p2.read()));
}

void SHA1ProcessMessageBlock::thread_tmp14_fu_1040_p2() {
    tmp14_fu_1040_p2 = (!E_2_reg_455.read().is_01() || !tmp_33_fu_1028_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(E_2_reg_455.read()) + sc_biguint<32>(tmp_33_fu_1028_p2.read()));
}

void SHA1ProcessMessageBlock::thread_tmp15_fu_1086_p2() {
    tmp15_fu_1086_p2 = (B_read_assign_3_reg_558.read() ^ E_6_reg_534.read());
}

void SHA1ProcessMessageBlock::thread_tmp16_fu_1192_p2() {
    tmp16_fu_1192_p2 = (!W_q1.read().is_01() || !tmp_72_i4_fu_1184_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(W_q1.read()) + sc_biguint<32>(tmp_72_i4_fu_1184_p3.read()));
}

void SHA1ProcessMessageBlock::thread_tmp17_fu_1109_p2() {
    tmp17_fu_1109_p2 = (!tmp18_fu_1103_p2.read().is_01() || !tmp_40_fu_1092_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp18_fu_1103_p2.read()) + sc_biguint<32>(tmp_40_fu_1092_p2.read()));
}

void SHA1ProcessMessageBlock::thread_tmp18_fu_1103_p2() {
    tmp18_fu_1103_p2 = (!ap_const_lv32_CA62C1D6.is_01() || !E_3_reg_524.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_CA62C1D6) + sc_biguint<32>(E_3_reg_524.read()));
}

void SHA1ProcessMessageBlock::thread_tmp3_fu_717_p2() {
    tmp3_fu_717_p2 = (W_load_reg_1266.read() ^ W_q1.read());
}

void SHA1ProcessMessageBlock::thread_tmp4_fu_722_p2() {
    tmp4_fu_722_p2 = (W_load_1_reg_1271.read() ^ W_q0.read());
}

void SHA1ProcessMessageBlock::thread_tmp5_fu_828_p2() {
    tmp5_fu_828_p2 = (!W_q0.read().is_01() || !tmp_72_i1_fu_796_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(W_q0.read()) + sc_biguint<32>(tmp_72_i1_fu_796_p3.read()));
}

void SHA1ProcessMessageBlock::thread_tmp6_fu_840_p2() {
    tmp6_fu_840_p2 = (!tmp7_fu_834_p2.read().is_01() || !E1_reg_322.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp7_fu_834_p2.read()) + sc_biguint<32>(E1_reg_322.read()));
}

void SHA1ProcessMessageBlock::thread_tmp7_fu_834_p2() {
    tmp7_fu_834_p2 = (!ap_const_lv32_5A827999.is_01() || !tmp_24_fu_822_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_5A827999) + sc_biguint<32>(tmp_24_fu_822_p2.read()));
}

void SHA1ProcessMessageBlock::thread_tmp8_fu_913_p2() {
    tmp8_fu_913_p2 = (B_read_assign_1_reg_421.read() ^ E_4_reg_397.read());
}

void SHA1ProcessMessageBlock::thread_tmp9_fu_925_p2() {
    tmp9_fu_925_p2 = (!W_q1.read().is_01() || !tmp_72_i2_fu_905_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(W_q1.read()) + sc_biguint<32>(tmp_72_i2_fu_905_p3.read()));
}

void SHA1ProcessMessageBlock::thread_tmp_10_fu_673_p2() {
    tmp_10_fu_673_p2 = (!ap_const_lv7_7D.is_01() || !t_1_reg_310.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_7D) + sc_biguint<7>(t_1_reg_310.read()));
}

void SHA1ProcessMessageBlock::thread_tmp_11_fu_679_p1() {
    tmp_11_fu_679_p1 = esl_zext<64,7>(tmp_10_fu_673_p2.read());
}

void SHA1ProcessMessageBlock::thread_tmp_12_fu_684_p2() {
    tmp_12_fu_684_p2 = (!ap_const_lv7_78.is_01() || !t_1_reg_310.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_78) + sc_biguint<7>(t_1_reg_310.read()));
}

void SHA1ProcessMessageBlock::thread_tmp_13_fu_690_p1() {
    tmp_13_fu_690_p1 = esl_zext<64,7>(tmp_12_fu_684_p2.read());
}

void SHA1ProcessMessageBlock::thread_tmp_14_fu_695_p2() {
    tmp_14_fu_695_p2 = (!ap_const_lv7_72.is_01() || !t_1_reg_310.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_72) + sc_biguint<7>(t_1_reg_310.read()));
}

void SHA1ProcessMessageBlock::thread_tmp_15_fu_701_p1() {
    tmp_15_fu_701_p1 = esl_zext<64,7>(tmp_14_fu_695_p2.read());
}

void SHA1ProcessMessageBlock::thread_tmp_16_fu_706_p2() {
    tmp_16_fu_706_p2 = (!ap_const_lv7_70.is_01() || !t_1_reg_310.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_70) + sc_biguint<7>(t_1_reg_310.read()));
}

void SHA1ProcessMessageBlock::thread_tmp_17_fu_712_p1() {
    tmp_17_fu_712_p1 = esl_zext<64,7>(tmp_16_fu_706_p2.read());
}

void SHA1ProcessMessageBlock::thread_tmp_18_fu_733_p1() {
    tmp_18_fu_733_p1 = word_assign_fu_727_p2.read().range(31-1, 0);
}

void SHA1ProcessMessageBlock::thread_tmp_19_fu_754_p1() {
    tmp_19_fu_754_p1 = esl_zext<64,7>(t_1_reg_310.read());
}

void SHA1ProcessMessageBlock::thread_tmp_1_fu_607_p3() {
    tmp_1_fu_607_p3 = esl_concat<4,2>(tmp_fu_603_p1.read(), ap_const_lv2_0);
}

void SHA1ProcessMessageBlock::thread_tmp_20_fu_737_p3() {
    tmp_20_fu_737_p3 = word_assign_fu_727_p2.read().range(31, 31);
}

void SHA1ProcessMessageBlock::thread_tmp_21_fu_804_p2() {
    tmp_21_fu_804_p2 = (D_1_reg_343.read() & B_read_assign_reg_354.read());
}

void SHA1ProcessMessageBlock::thread_tmp_22_fu_810_p2() {
    tmp_22_fu_810_p2 = (B_read_assign_reg_354.read() ^ ap_const_lv32_FFFFFFFF);
}

void SHA1ProcessMessageBlock::thread_tmp_23_fu_816_p2() {
    tmp_23_fu_816_p2 = (E_1_reg_332.read() & tmp_22_fu_810_p2.read());
}

void SHA1ProcessMessageBlock::thread_tmp_24_fu_822_p2() {
    tmp_24_fu_822_p2 = (tmp_23_fu_816_p2.read() | tmp_21_fu_804_p2.read());
}

void SHA1ProcessMessageBlock::thread_tmp_25_fu_777_p1() {
    tmp_25_fu_777_p1 = esl_zext<64,5>(t_2_reg_375.read());
}

void SHA1ProcessMessageBlock::thread_tmp_26_fu_782_p1() {
    tmp_26_fu_782_p1 = B_1_reg_364.read().range(27-1, 0);
}

void SHA1ProcessMessageBlock::thread_tmp_27_fu_852_p1() {
    tmp_27_fu_852_p1 = B_read_assign_reg_354.read().range(2-1, 0);
}

void SHA1ProcessMessageBlock::thread_tmp_28_fu_919_p2() {
    tmp_28_fu_919_p2 = (tmp8_fu_913_p2.read() ^ D_2_reg_409.read());
}

void SHA1ProcessMessageBlock::thread_tmp_29_fu_880_p1() {
    tmp_29_fu_880_p1 = esl_zext<64,6>(t_3_reg_444.read());
}

void SHA1ProcessMessageBlock::thread_tmp_2_fu_615_p1() {
    tmp_2_fu_615_p1 = esl_zext<64,6>(tmp_1_fu_607_p3.read());
}

void SHA1ProcessMessageBlock::thread_tmp_30_fu_1010_p2() {
    tmp_30_fu_1010_p2 = (E_5_reg_466.read() | D_3_reg_478.read());
}

void SHA1ProcessMessageBlock::thread_tmp_31_fu_1016_p2() {
    tmp_31_fu_1016_p2 = (tmp_30_fu_1010_p2.read() & B_read_assign_2_reg_490.read());
}

void SHA1ProcessMessageBlock::thread_tmp_32_fu_1022_p2() {
    tmp_32_fu_1022_p2 = (E_5_reg_466.read() & D_3_reg_478.read());
}

void SHA1ProcessMessageBlock::thread_tmp_33_fu_1028_p2() {
    tmp_33_fu_1028_p2 = (tmp_31_fu_1016_p2.read() | tmp_32_fu_1022_p2.read());
}

void SHA1ProcessMessageBlock::thread_tmp_34_fu_977_p1() {
    tmp_34_fu_977_p1 = esl_zext<64,6>(t_4_reg_513.read());
}

void SHA1ProcessMessageBlock::thread_tmp_35_fu_1143_p2() {
    tmp_35_fu_1143_p2 = (!A_reg_1291.read().is_01() || !B_4_reg_568.read().is_01())? sc_lv<32>(): (sc_biguint<32>(A_reg_1291.read()) + sc_biguint<32>(B_4_reg_568.read()));
}

void SHA1ProcessMessageBlock::thread_tmp_36_fu_1149_p2() {
    tmp_36_fu_1149_p2 = (!B_reg_1307.read().is_01() || !B_read_assign_3_reg_558.read().is_01())? sc_lv<32>(): (sc_biguint<32>(B_reg_1307.read()) + sc_biguint<32>(B_read_assign_3_reg_558.read()));
}

void SHA1ProcessMessageBlock::thread_tmp_37_fu_1155_p2() {
    tmp_37_fu_1155_p2 = (!C_reg_1313.read().is_01() || !D_4_reg_546.read().is_01())? sc_lv<32>(): (sc_biguint<32>(C_reg_1313.read()) + sc_biguint<32>(D_4_reg_546.read()));
}

void SHA1ProcessMessageBlock::thread_tmp_38_fu_1160_p2() {
    tmp_38_fu_1160_p2 = (!D_reg_1331.read().is_01() || !E_6_reg_534.read().is_01())? sc_lv<32>(): (sc_biguint<32>(D_reg_1331.read()) + sc_biguint<32>(E_6_reg_534.read()));
}

void SHA1ProcessMessageBlock::thread_tmp_39_fu_1165_p2() {
    tmp_39_fu_1165_p2 = (!E_reg_1337.read().is_01() || !E_3_reg_524.read().is_01())? sc_lv<32>(): (sc_biguint<32>(E_reg_1337.read()) + sc_biguint<32>(E_3_reg_524.read()));
}

void SHA1ProcessMessageBlock::thread_tmp_3_fu_636_p1() {
    tmp_3_fu_636_p1 = esl_zext<64,6>(tmp_s_fu_631_p2.read());
}

void SHA1ProcessMessageBlock::thread_tmp_40_fu_1092_p2() {
    tmp_40_fu_1092_p2 = (tmp15_fu_1086_p2.read() ^ D_4_reg_546.read());
}

void SHA1ProcessMessageBlock::thread_tmp_41_fu_1098_p1() {
    tmp_41_fu_1098_p1 = esl_zext<64,7>(t_5_reg_580.read());
}

void SHA1ProcessMessageBlock::thread_tmp_42_fu_891_p1() {
    tmp_42_fu_891_p1 = B_2_reg_432.read().range(27-1, 0);
}

void SHA1ProcessMessageBlock::thread_tmp_43_fu_949_p1() {
    tmp_43_fu_949_p1 = B_read_assign_1_reg_421.read().range(2-1, 0);
}

void SHA1ProcessMessageBlock::thread_tmp_44_fu_988_p1() {
    tmp_44_fu_988_p1 = B_3_reg_501.read().range(27-1, 0);
}

void SHA1ProcessMessageBlock::thread_tmp_45_fu_1058_p1() {
    tmp_45_fu_1058_p1 = B_read_assign_2_reg_490.read().range(2-1, 0);
}

void SHA1ProcessMessageBlock::thread_tmp_46_fu_1170_p1() {
    tmp_46_fu_1170_p1 = B_4_reg_568.read().range(27-1, 0);
}

void SHA1ProcessMessageBlock::thread_tmp_47_fu_1115_p1() {
    tmp_47_fu_1115_p1 = B_read_assign_3_reg_558.read().range(2-1, 0);
}

void SHA1ProcessMessageBlock::thread_tmp_4_fu_641_p2() {
    tmp_4_fu_641_p2 = (tmp_1_reg_1211.read() | ap_const_lv6_3);
}

void SHA1ProcessMessageBlock::thread_tmp_5_fu_651_p1() {
    tmp_5_fu_651_p1 = esl_zext<64,5>(t_reg_298.read());
}

void SHA1ProcessMessageBlock::thread_tmp_6_fu_620_p2() {
    tmp_6_fu_620_p2 = (tmp_1_fu_607_p3.read() | ap_const_lv6_1);
}

void SHA1ProcessMessageBlock::thread_tmp_71_i1_fu_786_p4() {
    tmp_71_i1_fu_786_p4 = B_1_reg_364.read().range(31, 27);
}

void SHA1ProcessMessageBlock::thread_tmp_71_i2_fu_895_p4() {
    tmp_71_i2_fu_895_p4 = B_2_reg_432.read().range(31, 27);
}

void SHA1ProcessMessageBlock::thread_tmp_71_i3_fu_992_p4() {
    tmp_71_i3_fu_992_p4 = B_3_reg_501.read().range(31, 27);
}

void SHA1ProcessMessageBlock::thread_tmp_71_i4_fu_1174_p4() {
    tmp_71_i4_fu_1174_p4 = B_4_reg_568.read().range(31, 27);
}

void SHA1ProcessMessageBlock::thread_tmp_71_i_i1_fu_953_p4() {
    tmp_71_i_i1_fu_953_p4 = B_read_assign_1_reg_421.read().range(31, 2);
}

void SHA1ProcessMessageBlock::thread_tmp_71_i_i2_fu_1062_p4() {
    tmp_71_i_i2_fu_1062_p4 = B_read_assign_2_reg_490.read().range(31, 2);
}

void SHA1ProcessMessageBlock::thread_tmp_71_i_i3_fu_1119_p4() {
    tmp_71_i_i3_fu_1119_p4 = B_read_assign_3_reg_558.read().range(31, 2);
}

void SHA1ProcessMessageBlock::thread_tmp_71_i_i_fu_856_p4() {
    tmp_71_i_i_fu_856_p4 = B_read_assign_reg_354.read().range(31, 2);
}

void SHA1ProcessMessageBlock::thread_tmp_72_i1_fu_796_p3() {
    tmp_72_i1_fu_796_p3 = esl_concat<27,5>(tmp_26_fu_782_p1.read(), tmp_71_i1_fu_786_p4.read());
}

void SHA1ProcessMessageBlock::thread_tmp_72_i2_fu_905_p3() {
    tmp_72_i2_fu_905_p3 = esl_concat<27,5>(tmp_42_fu_891_p1.read(), tmp_71_i2_fu_895_p4.read());
}

void SHA1ProcessMessageBlock::thread_tmp_72_i3_fu_1002_p3() {
    tmp_72_i3_fu_1002_p3 = esl_concat<27,5>(tmp_44_fu_988_p1.read(), tmp_71_i3_fu_992_p4.read());
}

void SHA1ProcessMessageBlock::thread_tmp_72_i4_fu_1184_p3() {
    tmp_72_i4_fu_1184_p3 = esl_concat<27,5>(tmp_46_fu_1170_p1.read(), tmp_71_i4_fu_1174_p4.read());
}

void SHA1ProcessMessageBlock::thread_tmp_7_fu_626_p1() {
    tmp_7_fu_626_p1 = esl_zext<64,6>(tmp_6_fu_620_p2.read());
}

void SHA1ProcessMessageBlock::thread_tmp_8_fu_646_p1() {
    tmp_8_fu_646_p1 = esl_zext<64,6>(tmp_4_fu_641_p2.read());
}

void SHA1ProcessMessageBlock::thread_tmp_fu_603_p1() {
    tmp_fu_603_p1 = t_reg_298.read().range(4-1, 0);
}

void SHA1ProcessMessageBlock::thread_tmp_s_fu_631_p2() {
    tmp_s_fu_631_p2 = (tmp_1_reg_1211.read() | ap_const_lv6_2);
}

void SHA1ProcessMessageBlock::thread_word_assign_fu_727_p2() {
    word_assign_fu_727_p2 = (tmp4_fu_722_p2.read() ^ tmp3_fu_717_p2.read());
}

void SHA1ProcessMessageBlock::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(exitcond5_fu_591_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        case 16 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_667_p2.read())) {
                ap_NS_fsm = ap_ST_st8_fsm_7;
            } else {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 1024 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_765_p2.read())) {
                ap_NS_fsm = ap_ST_st13_fsm_12;
            } else {
                ap_NS_fsm = ap_ST_st12_fsm_11;
            }
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 4096 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_874_p2.read())) {
                ap_NS_fsm = ap_ST_st15_fsm_14;
            } else {
                ap_NS_fsm = ap_ST_st14_fsm_13;
            }
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
            break;
        case 16384 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_971_p2.read())) {
                ap_NS_fsm = ap_ST_st17_fsm_16;
            } else {
                ap_NS_fsm = ap_ST_st16_fsm_15;
            }
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
            break;
        case 65536 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_1080_p2.read())) {
                ap_NS_fsm = ap_ST_st19_fsm_18;
            } else {
                ap_NS_fsm = ap_ST_st18_fsm_17;
            }
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_st20_fsm_19;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<20>) ("XXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void SHA1ProcessMessageBlock::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Intermediate_Hash_address0\" :  \"" << context_Intermediate_Hash_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Intermediate_Hash_ce0\" :  \"" << context_Intermediate_Hash_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Intermediate_Hash_we0\" :  \"" << context_Intermediate_Hash_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Intermediate_Hash_d0\" :  \"" << context_Intermediate_Hash_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"context_Intermediate_Hash_q0\" :  \"" << context_Intermediate_Hash_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Intermediate_Hash_address1\" :  \"" << context_Intermediate_Hash_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Intermediate_Hash_ce1\" :  \"" << context_Intermediate_Hash_ce1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Intermediate_Hash_we1\" :  \"" << context_Intermediate_Hash_we1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Intermediate_Hash_d1\" :  \"" << context_Intermediate_Hash_d1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"context_Intermediate_Hash_q1\" :  \"" << context_Intermediate_Hash_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Message_Block_Index\" :  \"" << context_Message_Block_Index.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Message_Block_Index_ap_vld\" :  \"" << context_Message_Block_Index_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Message_Block_address0\" :  \"" << context_Message_Block_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Message_Block_ce0\" :  \"" << context_Message_Block_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"context_Message_Block_q0\" :  \"" << context_Message_Block_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Message_Block_address1\" :  \"" << context_Message_Block_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"context_Message_Block_ce1\" :  \"" << context_Message_Block_ce1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"context_Message_Block_q1\" :  \"" << context_Message_Block_q1.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

